import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import { type CliEnv, run } from '../../src/cli.js';
import { DOD_ROWS, evaluateDod, expandItem, renderDod } from '../../src/dod.js';
import type { BriefInfo } from '../../src/ids.js';
import { parseGatesJson, renderItr } from '../../src/itr.js';
import { buildFileIndex, parsePgmTables, renderPgm, resolvePgm, resolveTokens } from '../../src/pgm.js';
import { median, parsePrf, renderPrf, verdict } from '../../src/prf.js';
import type { CaseResult } from '../../src/results.js';
import { auditHighCritical, renderSec, secByUnit } from '../../src/sec.js';
import { scanSource as scanSourceRaw } from '../../src/titles.js';

/**
 * 가짜 테스트 소스 안의 `IT(`·`TEST(` 를 `it(`·`test(` 로 되돌린다. 이 파일 안의 문자열을 정적 스캐너가
 * 실제 테스트 제목으로 읽지 않도록(중복 ID·위치 오탐 방지) 소스 문자열에는 대문자로 적는다.
 */
const fake = (text: string): string => text.replace(/\bIT(?=[.(])/g, 'it').replace(/\bTEST(?=[.(])/g, 'test');

const scanSource = (file: string, text: string): ReturnType<typeof scanSourceRaw> => scanSourceRaw(file, fake(text));

import { type CoverageSummary, renderUtr, unitLines, unitRows } from '../../src/utr.js';

const fixture = (name: string): string => readFileSync(new URL(`../fixtures/${name}`, import.meta.url), 'utf8');

const dirs: string[] = [];
afterEach(() => {
  for (const d of dirs.splice(0)) {
    rmSync(d, { recursive: true, force: true });
  }
});

function makeRepo(files: Record<string, string>): string {
  const root = mkdtempSync(path.join(os.tmpdir(), 'fathom-sid-rep-'));
  dirs.push(root);
  for (const [rel, text] of Object.entries(files)) {
    const abs = path.join(root, rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, fake(text));
  }
  return root;
}

function env(): { env: CliEnv; out: string[]; err: string[] } {
  const out: string[] = [];
  const err: string[] = [];
  return {
    out,
    err,
    env: {
      now: () => 1_790_000_000_000,
      commit: () => 'abc1234',
      nodeVersion: 'v22.22.2',
      out: (l) => out.push(l),
      err: (l) => err.push(l),
    },
  };
}

const MARK = '<!-- generated by tools/si-docs — 수기 편집 금지 (STD-DOC-07) -->';
const HEADER = '실행: 2026-10-01T00:00:00.000Z · 커밋: abc1234 · 명령: pnpm si:reports --int INT-1a · Node v22.22.2';

const c = (id: string | null, status: CaseResult['status'], over: Partial<CaseResult> = {}): CaseResult => ({
  id,
  title: id === null ? '묶음' : `${id} 동작 [FR-PRG-001]`,
  status,
  durationMs: 1000,
  suite: 'ut',
  file: 'x.spec.ts',
  ...over,
});

const rtmMd = fixture('rtm-mini.md');

/** 심볼릭 링크 디렉터리 경유로 cli.ts 를 직접 실행한다(isEntry realpath 비교 회귀: 침묵 exit 0 금지). */
function runViaSymlink(args: string[]): { status: number | null; stderr: string } {
  const srcDir = fileURLToPath(new URL('../../src/', import.meta.url));
  const dir = mkdtempSync(path.join(os.tmpdir(), 'fathom-cli-link-'));
  try {
    const link = path.join(dir, 'lnk');
    symlinkSync(srcDir, link, 'dir');
    const r = spawnSync(
      process.execPath,
      [
        '--disable-warning=ExperimentalWarning',
        '--import',
        'tsx',
        '--conditions=source',
        path.join(link, 'cli.ts'),
        ...args,
      ],
      { encoding: 'utf8', cwd: path.resolve(srcDir, '..') },
    );
    return { status: r.status, stderr: r.stderr };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

describe('결과서', () => {
  it('UT-SID-030 UTR 은 단위별 집계·domain 커버리지(직전 대비 %p)·커버리지 게이트·실패 상세·신규 케이스 매핑을 낸다 [UR-07][PR-007]', () => {
    const cov: CoverageSummary = {
      total: { lines: { total: 200, covered: 160, pct: 80 } },
      '/repo/services/learning/src/domain/practice/a.ts': { lines: { total: 50, covered: 45, pct: 90 } },
      '/repo/services/learning/src/application/b.ts': { lines: { total: 50, covered: 30, pct: 60 } },
      '/repo/services/content/src/domain/c.ts': { lines: { total: 100, covered: 84, pct: 84 } },
    };
    const prev: CoverageSummary = {
      total: { lines: { total: 1000, covered: 894, pct: 89.4 } },
      '/repo/services/learning/src/domain/practice/a.ts': { lines: { total: 1000, covered: 894, pct: 89.4 } },
    };
    expect(unitLines(cov, 'services/learning', true)).toEqual({ total: 50, covered: 45 });
    expect(unitLines(cov, 'services/learning', false)).toEqual({ total: 100, covered: 75 });
    expect(unitLines(null, 'services/learning', true)).toBeNull();
    expect(unitLines(cov, 'services/gateway', true)).toBeNull();
    const results = [
      c('UT-LR-001', 'pass'),
      c('UT-LR-002', 'pass'),
      c('UT-LR-003', 'fail', { message: 'AssertionError: expected 1 to be 2' }),
      c('UT-LR-004', 'skip'),
      c('UT-CT-001', 'pass'),
      c('IT-001', 'pass'),
      c(null, 'pass'),
    ];
    const rows = unitRows(results, cov, prev);
    expect(rows.map((r) => [r.unit, r.cases, r.pass, r.fail, r.skip])).toEqual([
      ['CT', 1, 1, 0, 0],
      ['LR', 4, 2, 1, 1],
    ]);
    const briefs: BriefInfo[] = [
      {
        taskId: 'T-02-01',
        file: 'b.md',
        ranges: [{ prefix: 'UT-LR', from: 1, to: 9 }],
        allowedPaths: [],
        fromYaml: true,
      },
    ];
    const titles = scanSource(
      'services/learning/test/unit/x.spec.ts',
      "IT('UT-LR-001 원장 [FR-PRG-001][NFR-DATA-013]', () => {});\nit('UT-CT-009 팩 [FR-CUR-001]', () => {});\n",
    ).titles;
    const md = renderUtr({
      int: 'INT-2',
      header: HEADER,
      results,
      coverage: cov,
      prevCoverage: prev,
      determinism: { equal: true },
      briefs,
      titles,
    });
    const lines = md.split('\n');
    expect(lines[0]).toBe(MARK);
    expect(lines[1]).toBe('# UTR-INT-2 단위테스트결과서 (자동 생성)');
    expect(lines[2]).toBe(`${HEADER} · 결정성 2회: 일치`);
    expect(md).toContain('| 단위 | 케이스 | 통과 | 실패 | 건너뜀 | domain 라인(직전 대비) | 전체 라인 |');
    expect(md).toContain('| learning (LR) | 4 | 2 | 1 | 1 | 90.0% (+0.6%p) | 75.0% |');
    expect(md).toContain('| content (CT) | 1 | 1 | 0 | 0 | 84.0% | 84.0% |');
    expect(md).toContain('| services/*/src/domain | ≥ 80%, 감소 ≤ 2%p | 최저 84.0% | PASS |');
    expect(md).toContain('전체 라인(total.lines.pct): 80.0%');
    expect(md).toContain('| UT-LR-003 | AssertionError: expected 1 to be 2 | — |');
    expect(md).toContain('| UT-LR-004 | 건너뜀(사유 미기재) | — |');
    expect(md).toContain('| UT-LR-001 | FR-PRG-001, NFR-DATA-013 | T-02-01 |');
    expect(md).toContain('| UT-CT-009 | FR-CUR-001 | — |');
    expect(md).toContain('## 커버리지 게이트');
    expect(md).toContain('## 실패 · 건너뜀 상세 (사유 필수)');
    expect(md).toContain('## 신규 케이스 → 요구 매핑 (RTM 반영)');
    // 커버리지·결정성 입력 없음 = n/a, 감소 2%p 초과 = FAIL
    const bare = renderUtr({
      int: 'INT-2',
      header: HEADER,
      results,
      coverage: null,
      prevCoverage: null,
      determinism: null,
      briefs: [],
      titles: [],
    });
    expect(bare).toContain('결정성 2회: n/a');
    expect(bare).toContain('| learning (LR) | 4 | 2 | 1 | 1 | n/a | n/a |');
    expect(bare).toContain('n/a (coverage-summary.json 없음) | n/a |');
    const dropped = renderUtr({
      int: 'INT-2',
      header: HEADER,
      results,
      coverage: cov,
      prevCoverage: { 'x/services/learning/src/domain/p.ts': { lines: { total: 100, covered: 95, pct: 95 } } },
      determinism: { equal: false },
      briefs: [],
      titles: [],
    });
    expect(dropped).toContain('결정성 2회: 불일치');
    expect(dropped).toContain('| services/*/src/domain | ≥ 80%, 감소 ≤ 2%p | 최저 84.0% | FAIL |');
    expect(dropped).toContain('90.0% (−5.0%p)');
  });

  it('UT-SID-031 ITR 은 §1~§6 절을 갖고 egress·격리·게이트·그래프 입력이 없으면 n/a 로 표기한다 [UR-07][PR-007]', () => {
    const results = [
      c('CT-LR-001', 'pass', { durationMs: 38_000 }),
      c('IT-001', 'pass', { durationMs: 9800, title: 'IT-001 채점 후 COMMIT 전 kill → 정확히 1건 [FR-PRG-001]' }),
      c('IT-002', 'fail', { message: '타임아웃' }),
      c('SEC-GW-001', 'pass'),
      c('E2E-001', 'pass'),
      c('CHA-001', 'skip'),
    ];
    const bare = renderItr({
      int: 'INT-3',
      header: HEADER,
      results,
      prf: null,
      gates: null,
      crossServiceEdgeCount: null,
      egress: null,
      quarantine: null,
    });
    const sections = bare.split('\n').filter((l) => l.startsWith('## '));
    expect(sections).toEqual([
      '## 1. 스위트 요약',
      '## 2. 케이스 결과',
      '## 3. 외부 호출 0 (egress.json)',
      '## 4. 격리(quarantine) 목록',
      '## 5. 정적 게이트 · 감사',
      '## 6. 판정(T1): (T1 기입)',
    ]);
    expect(bare.split('\n')[0]).toBe(MARK);
    expect(bare).toContain('# ITR-INT-3 통합테스트결과서 (자동 생성)');
    expect(bare).toContain('| contract (CT · CT-SYS) | 1/1 | — | 38.0s | PASS |');
    expect(bare).toContain('| integration (IT) | 1/2 | — | 10.8s | FAIL |');
    expect(bare).toContain('| chaos (CHA) | 0/1 | — | 1.0s | PASS |');
    expect(bare).toContain('| perf 빠른 세트 | 0/0 | — | — | n/a (prf.json 없음) |');
    expect(bare).toContain('| IT-001 | 채점 후 COMMIT 전 kill → 정확히 1건 | PASS | 9.8s | — |  |');
    expect(bare).toContain('| IT-002 | 동작 | FAIL | 1.0s | — | 타임아웃 |');
    expect(bare).toContain('n/a (egress.json 없음)');
    expect(bare).toContain('| ID | 결함 ID | 격리 시작 INT | 해제 예정 |');
    expect(bare).toContain('| check:gates | n/a (gates.json 없음) |  |');
    expect(bare).toContain('| audit:graph | n/a (metrics.json 없음) | 비차단 |');
    const gates = parseGatesJson({
      stage: 'g3',
      warn_only: false,
      exit: 1,
      gates: [
        { id: 'check:boundaries', script: 'x', exit: 0, errors: 0, warnings: 0, files: 145, ms: 5 },
        { id: 'check:deps', script: 'y', exit: 0, errors: 0, warnings: 0, files: 0, ms: 0, skipped: 'missing' },
        {
          id: 'check:rtm',
          script: 'z',
          exit: 2,
          errors: 0,
          warnings: 0,
          files: 0,
          ms: 1,
          error: 'engine/exception: boom',
        },
      ],
    });
    expect(gates?.gates).toHaveLength(3);
    const full = renderItr({
      int: 'INT-3',
      header: HEADER,
      results,
      prf: { runs: [{ id: 'PRF-001', target: 't', condition: 'c', threshold_ms: 2000, p95_ms: [1000, 1100, 1200] }] },
      gates,
      crossServiceEdgeCount: 0,
      egress: { isolation: 'L-hard', l1: 0, l2: 0, probe: { detected: true } },
      quarantine: [{ id: 'IT-055', defect_id: 'DEF-3', since_int: 'INT-2', release: 'INT-4' }],
    });
    expect(full).toContain('격리 수준: L-hard');
    expect(full).toContain('| isolation | L-hard |');
    expect(full).toContain('| probe | {"detected":true} |');
    expect(full).toContain('| IT-055 | DEF-3 | INT-2 | INT-4 |');
    expect(full).toContain('| check:gates --stage=g3 | exit 1 |  |');
    expect(full).toContain('| check:boundaries | PASS | errors=0 warnings=0 files=145 |');
    expect(full).toContain('| check:deps | skipped(missing) |');
    expect(full).toContain('| check:rtm | ERROR | engine/exception: boom |');
    expect(full).toContain('| audit:graph | 교차 서비스 파일 엣지 0 | 비차단 |');
    expect(full).toContain('| perf 빠른 세트 | 1/1 | — | — | PASS |');
    expect(parseGatesJson({ exit: 'x' })).toBeNull();
    expect(parseGatesJson({ exit: 0, gates: [{ id: 5 }] })).toBeNull();
  });

  it('UT-SID-032 PRF 는 중앙값이 임계 이하이고 어느 회차도 임계의 1.5배를 넘지 않을 때만 PASS 다 [UR-07][PR-007]', () => {
    expect(median([3, 1, 2])).toBe(2);
    expect(median([4, 1, 2, 3])).toBe(2.5);
    expect(median([])).toBeNull();
    const base = { id: 'PRF-001', target: '첫 문항', condition: 'OFFLINE 50회', threshold_ms: 2000 };
    expect(verdict({ ...base, p95_ms: [1500, 1800, 2100] })).toEqual({ median: 1800, pass: true, overRuns: [] });
    expect(verdict({ ...base, p95_ms: [1900, 3100, 1800] })).toEqual({ median: 1900, pass: false, overRuns: [2] });
    expect(verdict({ ...base, p95_ms: [2100, 2200, 1900] }).pass).toBe(false);
    expect(verdict({ ...base, p95_ms: [3000, 1000, 1000] }).pass).toBe(true);
    expect(verdict({ ...base, p95_ms: [] })).toEqual({ median: null, pass: false, overRuns: [] });
    const data = parsePrf({
      runs: [
        { id: 'PRF-001', target: '첫 문항', condition: 'OFFLINE 50회', threshold_ms: 2000, p95_ms: [1500, 1800, 2100] },
        { id: 'PRF-007', target: '검색 2만', condition: '120질의 × 10', threshold_ms: 100, p95_ms: [90, 95, 160, 80] },
      ],
      env: 'nproc 4',
    });
    expect(data?.runs).toHaveLength(2);
    expect(parsePrf({ runs: [{ id: 'PRF-001' }] })).toBeNull();
    expect(parsePrf([])).toBeNull();
    const md = renderPrf('INT-4', HEADER, data ?? { runs: [] });
    expect(md.split('\n')[0]).toBe(MARK);
    expect(md).toContain('# PRF-INT-4 성능 점검 결과 (자동 생성)');
    expect(md).toContain('환경: nproc 4');
    expect(md).toContain('| PRF | 대상 | 조건 | 임계 | run1 p95 | run2 p95 | run3 p95 | run4 p95 | 중앙값 | 판정 |');
    expect(md).toContain('| PRF-001 | 첫 문항 | OFFLINE 50회 | ≤ 2s | 1500ms | 1800ms | 2100ms | — | 1800ms | PASS |');
    expect(md).toContain(
      '| PRF-007 | 검색 2만 | 120질의 × 10 | ≤ 100ms | 90ms | 95ms | 160ms | 80ms | 92.5ms | FAIL |',
    );
    expect(md).toContain('| PRF-007 | run3 임계 × 1.5 초과 | 160ms > 150ms |');
    expect(md).toContain('## 추세(직전 전체 세트 대비)');
    expect(md).toContain('## 임계 위반 · 1.5배 초과 회차 상세');
  });

  it('UT-SID-033 SEC 는 audit high+critical 합·gates.json 의 check:security·SEC 케이스 UNIT별 통과 수를 낸다 [UR-07][PR-007]', () => {
    expect(
      auditHighCritical({ metadata: { vulnerabilities: { info: 0, low: 1, moderate: 2, high: 3, critical: 1 } } }),
    ).toBe(4);
    expect(auditHighCritical({ metadata: { vulnerabilities: {} } })).toBe(0);
    expect(auditHighCritical({ nope: true })).toBeNull();
    expect(auditHighCritical(null)).toBeNull();
    const results = [
      c('SEC-CT-001', 'pass'),
      c('SEC-CT-002', 'fail'),
      c('SEC-SYS-001', 'pass'),
      c('UT-LR-001', 'pass'),
    ];
    expect(secByUnit(results)).toEqual([
      { unit: 'CT', pass: 1, total: 2 },
      { unit: 'SYS', pass: 1, total: 1 },
    ]);
    const gates = parseGatesJson({
      stage: 'g3',
      exit: 0,
      gates: [{ id: 'check:security', exit: 0, errors: 0, warnings: 2, files: 9 }],
    });
    const md = renderSec({
      int: 'INT-4',
      header: HEADER,
      audit: { metadata: { vulnerabilities: { high: 1, critical: 1 } } },
      gates,
      results,
    });
    expect(md.split('\n')[0]).toBe(MARK);
    expect(md).toContain('# SEC-INT-4 보안약점 진단 결과 (자동 생성)');
    expect(md).toContain('| pnpm audit --prod --audit-level high (high + critical) | 2 | FAIL |');
    expect(md).toContain('| check:security | exit 0 | errors=0 warnings=2 |');
    expect(md).toContain('| SEC 케이스(전체) | 2/3 | FAIL |');
    expect(md).toContain('| SEC-CT (content) | 1/2 | FAIL |');
    expect(md).toContain('| SEC-SYS (system) | 1/1 | PASS |');
    for (const s of [
      '## 1. 자동 점검',
      '## 2. 항목별 점검',
      '## 3. 잔여 위험(RSK-RUN · 수용 위험) 변동',
      '## 4. 판정(T1): High 이상 미해결 0 / Medium 사유',
    ]) {
      expect(md).toContain(s);
    }
    const bare = renderSec({ int: 'INT-4', header: HEADER, audit: null, gates: null, results: [] });
    expect(bare).toContain('n/a (audit.json 없음)');
    expect(bare).toContain('n/a (gates.json 없음)');
  });

  it('UT-SID-034 DOD 는 TST §17 14행을 표로 만들고 범위를 확장해 PASS·FAIL·미실행을 판정한다 [UR-07][PR-007]', () => {
    expect(DOD_ROWS).toHaveLength(14);
    expect(DOD_ROWS.map((r) => r.d)).toEqual(Array.from({ length: 14 }, (_, i) => `D-${i + 1}`));
    expect(expandItem('E2E-301~321')).toHaveLength(21);
    expect(expandItem('E2E-301~321')[0]).toBe('E2E-301');
    expect(expandItem('E2E-301~321')[20]).toBe('E2E-321');
    expect(expandItem('IT-026')).toEqual(['IT-026']);
    const row = (d: string) => DOD_ROWS.find((r) => r.d === d) ?? DOD_ROWS[0];
    const d2 = row('D-2');
    if (d2 === undefined) {
      throw new Error('D-2 missing');
    }
    expect(evaluateDod(d2, [c('E2E-102', 'pass')], null).verdict).toBe('PASS');
    expect(evaluateDod(d2, [c('E2E-102', 'fail')], null).verdict).toBe('FAIL');
    expect(evaluateDod(d2, [c('E2E-102', 'skip')], null).verdict).toBe('FAIL');
    expect(evaluateDod(d2, [], null).verdict).toBe('미실행');
    const d9 = row('D-9');
    if (d9 === undefined) {
      throw new Error('D-9 missing');
    }
    const all9 = ['CHA-001', 'CHA-002', 'CHA-003', 'CHA-004', 'CHA-005', 'IT-019', 'IT-020'];
    expect(
      evaluateDod(
        d9,
        all9.map((id) => c(id, 'pass')),
        null,
      ).verdict,
    ).toBe('PASS');
    expect(
      evaluateDod(
        d9,
        all9.slice(1).map((id) => c(id, 'pass')),
        null,
      ).verdict,
    ).toBe('FAIL');
    expect(
      evaluateDod(
        d9,
        all9.map((id, i) => c(id, i === 3 ? 'fail' : 'pass')),
        null,
      ).verdict,
    ).toBe('FAIL');
    // 게이트 항목은 gates.json exit 로 판정
    const d10 = row('D-10');
    if (d10 === undefined) {
      throw new Error('D-10 missing');
    }
    const tests = [c('UT-TOK-001', 'pass'), c('E2E-501', 'pass')];
    const okGates = parseGatesJson({
      stage: 'g3',
      exit: 0,
      gates: [
        { id: 'check:ng-g', exit: 0 },
        { id: 'check:typo-ko', exit: 0 },
      ],
    });
    const badGates = parseGatesJson({
      stage: 'g3',
      exit: 1,
      gates: [
        { id: 'check:ng-g', exit: 0 },
        { id: 'check:typo-ko', exit: 1 },
      ],
    });
    expect(evaluateDod(d10, tests, okGates).verdict).toBe('PASS');
    expect(evaluateDod(d10, tests, badGates).verdict).toBe('FAIL');
    expect(evaluateDod(d10, tests, null).verdict).toBe('FAIL');
    const md = renderDod({
      int: 'INT-7',
      header: HEADER,
      results: [c('E2E-102', 'pass')],
      gates: null,
      platforms: null,
    });
    expect(md.split('\n')[0]).toBe(MARK);
    expect(md).toContain('# DOD-INT-7 Product DoD 판정서 (자동 생성)');
    expect(md.split('\n').filter((l) => /^\| D-\d+ \|.*\| (PASS|FAIL|미실행) \|/.test(l))).toHaveLength(14);
    expect(md).toContain('| D-2 | 설치 → 첫 세션 ≤ 3분 | E2E-102 | PASS |');
    expect(md).toContain('| D-3 | 첫 문항 p95 ≤ 2s | PRF-001(+ PRF-011 15년 규모) | 미실행 |');
    expect(md).toContain('## V-ci · V-live 상태(비게이트, 정직 표기)');
    expect(md.trimEnd().endsWith('## 판정: (T1 기입)')).toBe(true);
  });

  it('UT-SID-035 PGM 은 경로 열의 백틱 토큰을 glob 으로 확장하고 자리표시자는 *, 상태는 exists·partial·missing 3종이다 [UR-07][PR-007]', () => {
    const md = `${fixture('wbs-mini.md')}\n| PGM-ZZ-001 | LIB | x | \`services/none/src/**\` | 없음 | — | — | — | WP-99-99 |\n`;
    const parsed = parsePgmTables(md);
    expect(parsed.map((r) => r.id)).toEqual(['PGM-SYS-101', 'PGM-GATE-001', 'PGM-CT-001', 'PGM-CT-002']);
    expect(parsePgmTables(md.replace('PGM-ID', 'ID'))).toEqual([]);
    expect(parsed[0]?.paths).toEqual(['package.json', 'tsconfig*.json']);
    expect(parsed[2]?.paths).toEqual(['services/content/src/application/<bc>/install.ts', 'infra/packs/**']);
    expect(parsed[2]?.wp).toBe('WP-01-02');
    expect(resolveTokens(parsed[2]?.paths ?? [])).toEqual([
      'services/content/src/application/*/install.ts',
      'services/content/src/infra/packs/**',
    ]);
    const index = buildFileIndex([
      'package.json',
      'tsconfig.json',
      'tools/gates/lib/lex.mjs',
      'tools/gates/lib/common.mjs',
      'services/content/src/application/catalog/install.ts',
      'services/content/src/jobs/pack-load.ts',
    ]);
    const states = [
      ...parsed,
      { id: 'PGM-ZZ-001', type: 'LIB', unit: 'x', paths: ['services/none/src/**'], wp: 'WP-99-99' },
    ].map((r) => [r.id, resolvePgm(r, index).state]);
    expect(states).toEqual([
      ['PGM-SYS-101', 'exists'],
      ['PGM-GATE-001', 'exists'],
      ['PGM-CT-001', 'partial'],
      ['PGM-CT-002', 'exists'],
      ['PGM-ZZ-001', 'missing'],
    ]);
    expect(
      resolvePgm({ id: 'PGM-X-001', type: 'LIB', unit: 'x', paths: ['tools/gates/lib/'], wp: 'W' }, index).state,
    ).toBe('exists');
    expect(resolvePgm({ id: 'PGM-X-001', type: 'LIB', unit: 'x', paths: [], wp: 'W' }, index).state).toBe('missing');
    const results = parsed.map((r) => resolvePgm(r, index));
    const out = renderPgm('INT-1a', HEADER, results);
    expect(out.split('\n')[0]).toBe(MARK);
    expect(out).toContain('| PGM-ID | WP | 경로 | 상태 |');
    expect(out).toContain(
      '| PGM-CT-001 | WP-01-02 | services/content/src/application/<bc>/install.ts, infra/packs/** | partial |',
    );
    expect(out).toContain('| PGM-CT-001 | services/content/src/infra/packs/** |');
    expect(out).toContain('| PGM 수 | exists | partial | missing |');
  });

  it('UT-SID-036 cli 는 --int 형식 오류·알 수 없는 명령·옵션에 exit 2 이고 첫 인자가 -- 이면 reports 로 동작한다 [UR-07][PR-007]', () => {
    const repo = makeRepo({ 'docs/02-design/09-rtm.md': rtmMd });
    const common = ['--root', repo, '--min-reqs', '1'];
    for (const argv of [
      ['reports', '--int', 'INT-9', ...common],
      ['reports', '--int', 'int-1a', ...common],
      ['reports', ...common],
      ['rtm', '--int', 'PG-4', ...common],
      ['pgm', '--int', 'x', '--root', repo],
      ['frobnicate'],
      ['reports', '--int', 'INT-1a', '--bogus', '1'],
      ['reports', '--int'],
      ['reports', 'extra'],
      ['ids', '--iteration', 'abc', '--root', repo],
    ]) {
      const e = env();
      expect(run(argv, e.env), argv.join(' ')).toBe(2);
      expect(e.err.length).toBeGreaterThan(0);
    }
    // 심볼릭 링크 경유 직접 실행도 침묵 exit 0 이 아니라 실제로 run() 을 호출한다(잘못된 명령 → exit 2 + 오류 출력)
    const linked = runViaSymlink(['frobnicate']);
    expect(linked.status).toBe(2);
    expect(linked.stderr).toMatch(/\[si-docs\]/);
    const out = path.join(repo, 'out');
    const e = env();
    expect(run(['--int', 'INT-1a', ...common, '--out', out], e.env)).toBe(0);
    expect(readdirSync(out).sort()).toEqual(['ITR-INT-1a.md', 'RTM-INT-1a.md', 'UTR-INT-1a.md']);
    for (const id of ['INT-1a', 'INT-1b', 'INT-2', 'INT-7', 'PG-3']) {
      expect(run(['reports', '--int', id, ...common, '--out', out], env().env), id).toBe(0);
    }
  });

  it('UT-SID-037 cli 는 --out 과 <in>/rtm.json 에만 쓰고 모든 출력의 첫 줄이 생성 표지다 [UR-07][PR-007]', () => {
    const repo = makeRepo({ 'docs/02-design/09-rtm.md': rtmMd, 'README.md': '# repo\n' });
    const listing = (): string[] => {
      const all: string[] = [];
      const rec = (dir: string, rel: string): void => {
        for (const ent of readdirSync(dir, { withFileTypes: true })) {
          const r = rel === '' ? ent.name : `${rel}/${ent.name}`;
          if (ent.isDirectory()) {
            rec(path.join(dir, ent.name), r);
          } else {
            all.push(r);
          }
        }
      };
      rec(repo, '');
      return all.sort();
    };
    const before = listing();
    const outDir = path.join(repo, 'elsewhere', 'out');
    const inDir = path.join(repo, 'elsewhere', 'in');
    const e = env();
    expect(
      run(['reports', '--int', 'INT-1a', '--root', repo, '--min-reqs', '1', '--out', outDir, '--in', inDir], e.env),
    ).toBe(0);
    const added = listing().filter((f) => !before.includes(f));
    expect(added).toEqual([
      'elsewhere/in/rtm.json',
      'elsewhere/out/ITR-INT-1a.md',
      'elsewhere/out/RTM-INT-1a.md',
      'elsewhere/out/UTR-INT-1a.md',
    ]);
    expect(listing().filter((f) => before.includes(f))).toEqual(before);
    for (const f of added.filter((a) => a.endsWith('.md'))) {
      expect(readFileSync(path.join(repo, f), 'utf8').split('\n')[0], f).toBe(MARK);
    }
    expect(JSON.parse(readFileSync(path.join(inDir, 'rtm.json'), 'utf8')).version).toBe(1);
    expect(readFileSync(path.join(outDir, 'UTR-INT-1a.md'), 'utf8')).toContain('실행: 2026-');
    expect(readFileSync(path.join(outDir, 'UTR-INT-1a.md'), 'utf8')).toContain(
      '커밋: abc1234 · 명령: pnpm si:reports --int INT-1a · Node v22.22.2',
    );
    expect(e.out.some((l) => l.startsWith('[si-docs] INT-1a: 7 requirements'))).toBe(true);
  });

  it('UT-SID-038 cli 는 입력(vitest·Playwright·TAP·게이트·PRF·SEC·DoD)을 읽어 PRF·SEC·DOD 를 조건부로 만든다 [UR-07][PR-007]', () => {
    const inDir = '.reports/INT-1b';
    const prevCoverage = { 'x/services/learning/src/domain/a.ts': { lines: { total: 100, covered: 80, pct: 80 } } };
    const repo = makeRepo({
      'docs/02-design/09-rtm.md': rtmMd,
      [`${inDir}/ut.json`]: fixture('vitest-results.json'),
      [`${inDir}/e2e.json`]: fixture('playwright-results.json'),
      [`${inDir}/results.tap`]: fixture('results.tap'),
      [`${inDir}/sec.json`]: JSON.stringify({
        testResults: [
          {
            name: 'a',
            assertionResults: [
              { title: 'SEC-GW-001 쿠키 [NFR-SEC-001]', status: 'passed', duration: 1, failureMessages: [] },
            ],
          },
        ],
      }),
      [`${inDir}/audit.json`]: JSON.stringify({ metadata: { vulnerabilities: { high: 0, critical: 0 } } }),
      [`${inDir}/gates.json`]: JSON.stringify({
        stage: 'g3',
        warn_only: true,
        exit: 0,
        gates: [{ id: 'check:security', exit: 0, errors: 0, warnings: 0, files: 3, ms: 2 }],
      }),
      [`${inDir}/prf.json`]: JSON.stringify({
        runs: [
          { id: 'PRF-001', target: '첫 문항', condition: 'OFFLINE', threshold_ms: 2000, p95_ms: [1000, 1100, 1200] },
        ],
      }),
      [`${inDir}/coverage-summary.json`]: JSON.stringify({
        total: { lines: { total: 100, covered: 90, pct: 90 } },
        'x/services/learning/src/domain/a.ts': { lines: { total: 100, covered: 90, pct: 90 } },
      }),
      '.reports/INT-1a/coverage-summary.json': JSON.stringify(prevCoverage),
      [`${inDir}/determinism.json`]: '{"equal": true}',
      [`${inDir}/egress.json`]: '{"isolation":"L-js","l1":0}',
      [`${inDir}/quarantine.json`]: '[]',
      'services/learning/.reports/ut.json': JSON.stringify({
        testResults: [
          {
            name: 'p',
            assertionResults: [
              { title: 'UT-LR-099 패키지 실행분 [FR-PRG-001]', status: 'passed', duration: 2, failureMessages: [] },
            ],
          },
        ],
      }),
      'docs/40-impl/graph/INT-1b/metrics.json': '{"cross_service_edge_count": 0}',
    });
    const out = path.join(repo, 'out');
    expect(
      run(['reports', '--int', 'INT-1b', '--root', repo, '--min-reqs', '1', '--out', out, '--dod'], env().env),
    ).toBe(0);
    expect(readdirSync(out).sort()).toEqual([
      'DOD-INT-1b.md',
      'ITR-INT-1b.md',
      'PRF-INT-1b.md',
      'RTM-INT-1b.md',
      'SEC-INT-1b.md',
      'UTR-INT-1b.md',
    ]);
    const utr = readFileSync(path.join(out, 'UTR-INT-1b.md'), 'utf8');
    expect(utr).toContain('| learning (LR) | 4 | 2 | 1 | 1 | 90.0% (+10.0%p) | 90.0% |');
    expect(utr).toContain('결정성 2회: 일치');
    expect(utr).toContain('| gates (GATE) | 4 | 1 | 1 | 2 |');
    const itr = readFileSync(path.join(out, 'ITR-INT-1b.md'), 'utf8');
    expect(itr).toContain('| e2e (E2E) | 2/4 | — | 31.9s | FAIL |');
    expect(itr).toContain('격리 수준: L-js');
    expect(itr).toContain('| audit:graph | 교차 서비스 파일 엣지 0 | 비차단 |');
    expect(readFileSync(path.join(out, 'SEC-INT-1b.md'), 'utf8')).toContain('| SEC-GW (gateway) | 1/1 | PASS |');
    const rtm = JSON.parse(readFileSync(path.join(repo, inDir, 'rtm.json'), 'utf8')) as {
      requirements: { id: string; tests: { id: string; status: string }[] }[];
    };
    expect(rtm.requirements.find((r) => r.id === 'FR-PRG-001')?.tests.map((t) => `${t.id}:${t.status}`)).toEqual([
      'UT-LR-012:pass',
      'UT-LR-013:fail',
      'UT-LR-014:skip',
      'UT-LR-099:pass',
    ]);
    // INT-7 은 --dod 없이도 DOD, 입력이 없으면 PRF·SEC 는 만들지 않는다
    const out2 = path.join(repo, 'out2');
    expect(
      run(
        [
          'reports',
          '--int',
          'INT-7',
          '--root',
          repo,
          '--min-reqs',
          '1',
          '--out',
          out2,
          '--in',
          path.join(repo, 'empty-in'),
        ],
        env().env,
      ),
    ).toBe(0);
    expect(readdirSync(out2).sort()).toEqual(['DOD-INT-7.md', 'ITR-INT-7.md', 'RTM-INT-7.md', 'UTR-INT-7.md']);
    // 깨진 JSON 입력 = exit 2
    writeFileSync(path.join(repo, inDir, 'gates.json'), '{ nope');
    const bad = env();
    expect(run(['reports', '--int', 'INT-1b', '--root', repo, '--min-reqs', '1', '--out', out], bad.env)).toBe(2);
    expect(bad.err.join('\n')).toMatch(/invalid JSON/);
  });

  it('UT-SID-039 cli ids·pgm 명령은 저장소를 검사해 보고하고 pgm 은 누락이 있어도 exit 0 이다 [UR-07][PR-007]', () => {
    const wbs = `${fixture('wbs-mini.md').trimEnd()}\n| PGM-ZZ-001 | LIB | x | \`services/none/src/**\` | 없음 | — | — | — | WP-99-99 |\n`;
    const repo = makeRepo({
      'docs/02-design/08-wbs-iteration-plan.md': wbs,
      'package.json': '{}',
      'tools/gates/lib/lex.mjs': '',
      'services/content/src/jobs/pack-load.ts': '',
      'tools/si-docs/test/unit/a.spec.ts': "IT('UT-SID-001 동작 [FR-PRG-001]', () => {});\n",
      'tools/si-docs/test/integration/b.spec.ts':
        "IT('UT-SID-002 패키지 integration UT 는 허용 [FR-PRG-001]', () => {});\n",
      'services/learning/test/integration/c.spec.ts':
        "IT('UT-LR-001 services integration UT 는 위반 [FR-PRG-001]', () => {});\nit('IT-250 대역 밖 [FR-PRG-001]', () => {});\n",
    });
    const ids = env();
    expect(run(['ids', '--root', repo], ids.env)).toBe(1);
    const text = ids.out.join('\n');
    expect(text).toMatch(/c\.spec\.ts:1 {2}error {2}si\/id-location/);
    expect(text).toMatch(/c\.spec\.ts:2 {2}error {2}si\/it-band/);
    expect(text).not.toMatch(/a\.spec\.ts/);
    expect(text).not.toMatch(/b\.spec\.ts/);
    expect(ids.out.at(-1)).toBe('[si:ids] 2 error(s), 4 test ID(s) in 3 file(s)');
    const out = path.join(repo, 'out');
    const pgm = env();
    expect(run(['pgm', '--int', 'INT-1a', '--root', repo, '--out', out], pgm.env)).toBe(0);
    const md = readFileSync(path.join(out, 'PGM-INT-1a.md'), 'utf8');
    expect(md.split('\n')[0]).toBe(MARK);
    expect(md).toContain('| PGM-SYS-101 | WP-00-01 | package.json, tsconfig*.json | partial |');
    expect(md).toContain('| PGM-GATE-001 | WP-00-10 | tools/gates/lib/{lex,common}.mjs | partial |');
    expect(md).toContain('| PGM-CT-002 | WP-01-02 | services/content/src/jobs/pack-load.ts | exists |');
    expect(md).toContain('| PGM-ZZ-001 | WP-99-99 | services/none/src/** | missing |');
    expect(run(['pgm', '--int', 'INT-1a', '--root', path.join(repo, 'absent')], env().env)).toBe(2);
    const noRows = makeRepo({ 'docs/02-design/08-wbs-iteration-plan.md': '# 표 없음\n' });
    const e = env();
    expect(run(['pgm', '--int', 'INT-1a', '--root', noRows], e.env)).toBe(2);
    expect(e.err.join('\n')).toMatch(/ambiguity/);
  });
});
