import { SHA, ULID_A, ULID_B, ULID_C } from './fixtures.js';

const VERDICT = {
  verdict_id: ULID_B,
  attempt_id: ULID_A,
  session_id: ULID_C,
  block_id: null,
  item_id: 'docker.dockerfile.i05',
  item_content_hash: SHA,
  item_beta_snapshot: 0,
  item_n_options: 2,
  gate_result_id: null,
  stakes: 'S0',
  concept_id: 'docker.dockerfile',
  ku_ids: [],
  mc_ids: [],
  facet: 'concept',
  format: 'ox',
  response_mode: 'recognition',
  tier: 'A',
  result: 'correct',
  band: 'right',
  score: 1,
  confidence: null,
  latency_ms: 1000,
  rapid: false,
  hints_used: 0,
  grader_engine: 'D',
  calibrated: false,
  grader_confidence: null,
  pending: false,
  provisional: false,
  w_format: 1,
  w_grader: 1,
  gaming_factor: 1,
  recommended_grade: 3,
  ai_mode: 'OFFLINE',
  content_policy_version: 'ps_0123456789abcdef',
  judge_log_ref: null,
  prompt_version: null,
  issued_at: 1_790_000_000_000,
};

/** 17종 대표 payload(EVENT_PAYLOADS[type][1]을 통과하는 최소 값). */
export const EVENT_FIXTURES: Readonly<Record<string, Record<string, unknown>>> = {
  'catalog.pack.activated': {
    pack_id: 'k8s',
    track: 'k8s',
    version: '1.0.0',
    channel: 'seed',
    manifest_hash: SHA,
    merkle_root: SHA,
    previous_version: null,
    changed_concept_ids: ['k8s.probes'],
    changed_ku_ids: [],
    offline_cap_level: 3,
    catalog_version: 1,
    activated_at: 1_790_000_000_000,
  },
  'catalog.overlay.conflicted': {
    conflict_id: ULID_A,
    patch_id: ULID_B,
    target_kind: 'concept',
    target_id: 'docker.dockerfile',
    field: 'title',
    base_version: SHA,
    new_base_version: SHA,
  },
  'acquisition.import.staged': {
    job_id: ULID_A,
    source_kind: 'url',
    diff_summary: { concepts: 1, kus: 2, items: 3 },
    requires_approval: true,
  },
  'grading.verdict.revised': {
    verdict: VERDICT,
    supersedes_verdict_id: ULID_A,
    reason: 'appeal',
    band_changed: false,
  },
  'itembank.item.corrected': {
    item_id: 'docker.dockerfile.i05',
    correction: 'key_fixed',
    evidence_policy: 'void',
    basis: 'report',
    gate_result_id: ULID_A,
    effective_from: 1_790_000_000_000,
  },
  'learning.session.completed': {
    session_id: ULID_A,
    scope: null,
    template: 'standard',
    blocks_total: 3,
    blocks_done: 3,
    modes: ['M-03'],
    duration_ms: 60_000,
    first_item_latency_ms: null,
    completed_at: 1_790_000_000_000,
  },
  'learning.mastery.changed': { concept_id: 'k8s.probes', from: 'learning', to: 'mastered', provisional: false },
  'learning.level.promoted': {
    track: 'docker',
    from_level: 2,
    to_level: 3,
    provisional: false,
    profile: { policy_version: 'ps_0123456789abcdef', ai_mode: 'OFFLINE' },
  },
  'learning.ledger.merged': { checkpoint_id: ULID_A, root_hash: SHA, imported_events: 0, devices: [] },
  'ai.mode.changed': {
    mode: 'FULL',
    previous_mode: 'OFFLINE',
    reasons: ['probe_ok'],
    providers: [],
    changed_at: 1_790_000_000_000,
  },
  'ai.provider.status_changed': { provider_id: 'jev', status: 'ok', breaker: 'closed', reason_code: null },
  'ai.work_order.approval_requested': {
    work_order_id: ULID_A,
    purpose: 'import',
    estimate: { calls: 1, krw: 100, quota_pct: 1, duration_s: 10 },
    requested_by: 'user',
  },
  'ai.work_order.decided': { work_order_id: ULID_A, decision: 'approved', reservation: null },
  'ai.budget.threshold_reached': { scope: 'money', provider_id: null, ratio: 0.8, period: '2026-10' },
  'ai.judge.drift_detected': {
    provider_id: 'jev',
    task_id: 'AI-J01',
    model_version_prev: 'a',
    model_version_new: 'b',
  },
  'ops.health.changed': {
    services: [
      { svc: 'content', state: 'ready', restarts_60s: 0 },
      { svc: 'learning', state: 'ready', restarts_60s: 0 },
    ],
    degraded: [],
    outbox_lag: [],
    banners: [],
  },
  'ops.backup.completed': { epoch_id: ULID_A, kind: 'snapshot', outcome: 'ok', reason: null, rpo_hours: 1 },
};

/** SSE 프레임 data 줄(JSON 문자열). */
export function sseData(type: string, payload: Record<string, unknown>, schemaVersion = 1): string {
  return JSON.stringify({
    type,
    schema_version: schemaVersion,
    event_id: ULID_A,
    occurred_at: 1_790_000_000_000,
    correlation_id: ULID_B,
    producer: 'learning',
    payload,
  });
}
