// 원장 payload 유효 샘플(테스트 전용). 키 = LedgerEventType.
export const U1 = '01HZX3Y5K7M9N2P4Q6R8S0T1V2';
export const U2 = '01J0A1B2C3D4E5F6G7H8J9K0M1';
export const U3 = '01J1N2P3Q4R5S6T7V8W9X0Y1Z2';
export const SHA = 'a'.repeat(64);
export const PS = 'ps_0123456789abcdef';
export const PS2 = 'ps_fedcba9876543210';
export const DAY = '2026-10-01';

export const verdictCarried = (): Record<string, unknown> => ({
  verdict_id: U1,
  attempt_id: U2,
  session_id: U3,
  block_id: null,
  item_id: 'docker.dockerfile.i05',
  item_content_hash: SHA,
  item_beta: 0.2,
  item_n_options: 4,
  gate_result_id: null,
  stakes: 'S1',
  concept_id: 'docker.dockerfile',
  ku_ids: ['docker.dockerfile.k01'],
  mc_ids: [],
  facet: 'concept',
  format: 'mcq',
  response_mode: 'recognition',
  tier: 'A',
  result: 'correct',
  band: 'right',
  score: 1,
  confidence: 2,
  latency_ms: 4200,
  rapid: false,
  hints_used: 0,
  grader_engine: 'D',
  calibrated: false,
  grader_confidence: null,
  pending: false,
  provisional: false,
  w_format: 0.6,
  w_grader: 1,
  gaming_factor: 1,
  recommended_grade: 3,
  ai_mode: 'OFFLINE',
  content_policy_version: 'cp-1',
  judge_log_ref: null,
  prompt_version: null,
  issued_at: 1_759_000_000_000,
});

export const CARD = 'docker.dockerfile:concept:r';
export const PROFILE = { policy_version: PS, ai_mode: 'OFFLINE', sp1_state: 'unknown' };

export const examItems = (): string[] =>
  Array.from({ length: 12 }, (_, i) => `docker.dockerfile.i${String(i + 1).padStart(2, '0')}`);

export const PAYLOAD_SAMPLES: Record<string, () => Record<string, unknown>> = {
  'attempt.graded': () => ({
    ...verdictCarried(),
    card_id: CARD,
    phase: 'practice',
    rating: 3,
    cbm_score: null,
    fsrs_at: 1_759_000_000_000,
    study_day: DAY,
    policy_version: PS,
  }),
  'evidence.upgraded': () => ({
    ...verdictCarried(),
    supersedes_event_id: U2,
    supersedes_verdict_id: U3,
    card_id: CARD,
    new_rating: 4,
    rating_applied: false,
    study_day: DAY,
    policy_version: PS,
  }),
  'evidence.regraded': () => ({
    ...verdictCarried(),
    supersedes_event_id: U2,
    supersedes_verdict_id: U3,
    card_id: CARD,
    reason: 'appeal',
    new_rating: null,
    rating_applied: false,
    study_day: DAY,
    policy_version: PS,
  }),
  'evidence.voided': () => ({
    item_id: 'docker.dockerfile.i05',
    target_event_ids: [U1, U2],
    basis: 'regate_g3',
    correction: 'quarantined',
    gate_result_id: U3,
    study_day: DAY,
    policy_version: PS,
  }),
  'evidence.weight_adjusted': () => ({
    target_event_ids: [U1],
    adjustment: { kind: 'factor', factor: 0.5 },
    cause: 'correction_halve',
    item_id: 'docker.dockerfile.i05',
    gate_result_id: U3,
    study_day: DAY,
    policy_version: PS,
  }),
  'pretest.answered': () => ({
    attempt_id: U1,
    verdict_id: U2,
    item_id: 'docker.dockerfile.i05',
    item_content_hash: SHA,
    concept_id: 'docker.dockerfile',
    item_beta: -0.3,
    item_n_options: 4,
    result: 'incorrect',
    latency_ms: 1000,
    study_day: DAY,
    policy_version: PS,
  }),
  'lesson.completed': () => ({
    concept_id: 'docker.dockerfile',
    session_id: U1,
    block_id: U2,
    stage: 'theory',
    duration_ms: 60_000,
    study_day: DAY,
    policy_version: PS,
  }),
  'self_assessment.recorded': () => ({
    kind: 'jol',
    target: { kind: 'concept', id: 'docker.dockerfile' },
    value: { kind: 'probability', p: 0.7 },
    session_id: null,
    study_day: DAY,
    policy_version: PS,
  }),
  'card.enrolled': () => ({
    card_id: CARD,
    concept_id: 'docker.dockerfile',
    facet: 'concept',
    response_mode: 'recognition',
    tier: 'A',
    study_day: DAY,
    policy_version: PS,
  }),
  'card.status_changed': () => ({
    card_id: CARD,
    status: 'suspended',
    reason: 'leech',
    study_day: DAY,
    policy_version: PS,
  }),
  'profile.setting_changed': () => ({
    key: 'rhythm.day_start',
    from: '04:00',
    to: { hour: 5, minute: 0 },
    study_day: DAY,
  }),
  'policy.switched': () => ({
    policy_version: PS2,
    previous_policy_version: PS,
    members: { mastery_rules: { version: 'mastery_rules@v1', sha256: SHA } },
    overrides_sha256: null,
    replay_report_ref: null,
    study_day: DAY,
  }),
  'ai_mode.observed': () => ({
    mode: 'FULL',
    providers: [{ id: 'anthropic-api', kind: 'llm_api', status: 'ok' }],
    source_event_id: U1,
    observed_at: 1_759_000_000_000,
    study_day: DAY,
  }),
  'declaration.sealed': () => ({
    declaration_id: U1,
    kind: 'time_capsule',
    content_hash: SHA,
    sealed_payload: { text: '미래의 나에게' },
    unseal_at: null,
    study_day: DAY,
  }),
  'promotion.exam_completed': () => ({
    exam_id: U1,
    track: 'docker',
    level: 2,
    item_ids: examItems(),
    formats: ['mcq', 'cloze', 'short', 'ox'],
    correct_count: 10,
    cbm_ratio: 0.8,
    passed: true,
    profile: { ...PROFILE },
    study_day: DAY,
  }),
  'level.promoted': () => ({
    track: 'docker',
    from: null,
    to: 1,
    provisional: false,
    basis: 'placement',
    gates: [
      {
        gate_id: 'FORMATS',
        label_ko: '형식 다양성',
        met: true,
        value: 4,
        threshold: 3,
        evidence_event_ids: [U1],
        shortfall_ko: null,
      },
    ],
    profile: { ...PROFILE },
    study_day: DAY,
  }),
  'level.provisional_resolved': () => ({
    track: 'docker',
    level: 2,
    outcome: 'confirmed',
    needs_reconfirmation: false,
    regrade_verdict_ids: [U1],
    study_day: DAY,
  }),
};
