/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routing/__root.tsx';
import { Route as IndexRouteImport } from './routing/index.tsx';
import { Route as DesignRouteImport } from './routing/[_]design.tsx';
import { Route as AiRouteImport } from './routing/ai.tsx';
import { Route as CurationRouteImport } from './routing/curation.tsx';
import { Route as InboxRouteImport } from './routing/inbox.tsx';
import { Route as MapRouteImport } from './routing/map.tsx';
import { Route as OpsRouteImport } from './routing/ops.tsx';
import { Route as SeasonRouteImport } from './routing/season.tsx';
import { Route as SettingsRouteImport } from './routing/settings.tsx';
import { Route as ArtifactsRunIdRouteImport } from './routing/artifacts.$runId.tsx';
import { Route as CasesRunIdRouteImport } from './routing/cases.$runId.tsx';
import { Route as ConceptsConceptIdRouteImport } from './routing/concepts.$conceptId.tsx';
import { Route as DigDialogIdRouteImport } from './routing/dig.$dialogId.tsx';
import { Route as EvidenceConceptIdRouteImport } from './routing/evidence.$conceptId.tsx';
import { Route as ImportsJobIdRouteImport } from './routing/imports.$jobId.tsx';
import { Route as NotesBlockIdRouteImport } from './routing/notes.$blockId.tsx';
import { Route as ReviewWeeklyRouteImport } from './routing/review.weekly.tsx';
import { Route as SessionSessionIdRouteImport } from './routing/session.$sessionId.tsx';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const DesignRoute = DesignRouteImport.update({
  id: '/_design',
  path: '/_design',
  getParentRoute: () => rootRouteImport,
} as any);
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any);
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any);
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any);
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any);
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any);
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const ArtifactsRunIdRoute = ArtifactsRunIdRouteImport.update({
  id: '/artifacts/$runId',
  path: '/artifacts/$runId',
  getParentRoute: () => rootRouteImport,
} as any);
const CasesRunIdRoute = CasesRunIdRouteImport.update({
  id: '/cases/$runId',
  path: '/cases/$runId',
  getParentRoute: () => rootRouteImport,
} as any);
const ConceptsConceptIdRoute = ConceptsConceptIdRouteImport.update({
  id: '/concepts/$conceptId',
  path: '/concepts/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any);
const DigDialogIdRoute = DigDialogIdRouteImport.update({
  id: '/dig/$dialogId',
  path: '/dig/$dialogId',
  getParentRoute: () => rootRouteImport,
} as any);
const EvidenceConceptIdRoute = EvidenceConceptIdRouteImport.update({
  id: '/evidence/$conceptId',
  path: '/evidence/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any);
const ImportsJobIdRoute = ImportsJobIdRouteImport.update({
  id: '/imports/$jobId',
  path: '/imports/$jobId',
  getParentRoute: () => rootRouteImport,
} as any);
const NotesBlockIdRoute = NotesBlockIdRouteImport.update({
  id: '/notes/$blockId',
  path: '/notes/$blockId',
  getParentRoute: () => rootRouteImport,
} as any);
const ReviewWeeklyRoute = ReviewWeeklyRouteImport.update({
  id: '/review/weekly',
  path: '/review/weekly',
  getParentRoute: () => rootRouteImport,
} as any);
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/_design': typeof DesignRoute;
  '/ai': typeof AiRoute;
  '/curation': typeof CurationRoute;
  '/inbox': typeof InboxRoute;
  '/map': typeof MapRoute;
  '/ops': typeof OpsRoute;
  '/season': typeof SeasonRoute;
  '/settings': typeof SettingsRoute;
  '/artifacts/$runId': typeof ArtifactsRunIdRoute;
  '/cases/$runId': typeof CasesRunIdRoute;
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute;
  '/dig/$dialogId': typeof DigDialogIdRoute;
  '/evidence/$conceptId': typeof EvidenceConceptIdRoute;
  '/imports/$jobId': typeof ImportsJobIdRoute;
  '/notes/$blockId': typeof NotesBlockIdRoute;
  '/review/weekly': typeof ReviewWeeklyRoute;
  '/session/$sessionId': typeof SessionSessionIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/_design': typeof DesignRoute;
  '/ai': typeof AiRoute;
  '/curation': typeof CurationRoute;
  '/inbox': typeof InboxRoute;
  '/map': typeof MapRoute;
  '/ops': typeof OpsRoute;
  '/season': typeof SeasonRoute;
  '/settings': typeof SettingsRoute;
  '/artifacts/$runId': typeof ArtifactsRunIdRoute;
  '/cases/$runId': typeof CasesRunIdRoute;
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute;
  '/dig/$dialogId': typeof DigDialogIdRoute;
  '/evidence/$conceptId': typeof EvidenceConceptIdRoute;
  '/imports/$jobId': typeof ImportsJobIdRoute;
  '/notes/$blockId': typeof NotesBlockIdRoute;
  '/review/weekly': typeof ReviewWeeklyRoute;
  '/session/$sessionId': typeof SessionSessionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_design': typeof DesignRoute;
  '/ai': typeof AiRoute;
  '/curation': typeof CurationRoute;
  '/inbox': typeof InboxRoute;
  '/map': typeof MapRoute;
  '/ops': typeof OpsRoute;
  '/season': typeof SeasonRoute;
  '/settings': typeof SettingsRoute;
  '/artifacts/$runId': typeof ArtifactsRunIdRoute;
  '/cases/$runId': typeof CasesRunIdRoute;
  '/concepts/$conceptId': typeof ConceptsConceptIdRoute;
  '/dig/$dialogId': typeof DigDialogIdRoute;
  '/evidence/$conceptId': typeof EvidenceConceptIdRoute;
  '/imports/$jobId': typeof ImportsJobIdRoute;
  '/notes/$blockId': typeof NotesBlockIdRoute;
  '/review/weekly': typeof ReviewWeeklyRoute;
  '/session/$sessionId': typeof SessionSessionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/_design'
    | '/ai'
    | '/curation'
    | '/inbox'
    | '/map'
    | '/ops'
    | '/season'
    | '/settings'
    | '/artifacts/$runId'
    | '/cases/$runId'
    | '/concepts/$conceptId'
    | '/dig/$dialogId'
    | '/evidence/$conceptId'
    | '/imports/$jobId'
    | '/notes/$blockId'
    | '/review/weekly'
    | '/session/$sessionId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/_design'
    | '/ai'
    | '/curation'
    | '/inbox'
    | '/map'
    | '/ops'
    | '/season'
    | '/settings'
    | '/artifacts/$runId'
    | '/cases/$runId'
    | '/concepts/$conceptId'
    | '/dig/$dialogId'
    | '/evidence/$conceptId'
    | '/imports/$jobId'
    | '/notes/$blockId'
    | '/review/weekly'
    | '/session/$sessionId';
  id:
    | '__root__'
    | '/'
    | '/_design'
    | '/ai'
    | '/curation'
    | '/inbox'
    | '/map'
    | '/ops'
    | '/season'
    | '/settings'
    | '/artifacts/$runId'
    | '/cases/$runId'
    | '/concepts/$conceptId'
    | '/dig/$dialogId'
    | '/evidence/$conceptId'
    | '/imports/$jobId'
    | '/notes/$blockId'
    | '/review/weekly'
    | '/session/$sessionId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DesignRoute: typeof DesignRoute;
  AiRoute: typeof AiRoute;
  CurationRoute: typeof CurationRoute;
  InboxRoute: typeof InboxRoute;
  MapRoute: typeof MapRoute;
  OpsRoute: typeof OpsRoute;
  SeasonRoute: typeof SeasonRoute;
  SettingsRoute: typeof SettingsRoute;
  ArtifactsRunIdRoute: typeof ArtifactsRunIdRoute;
  CasesRunIdRoute: typeof CasesRunIdRoute;
  ConceptsConceptIdRoute: typeof ConceptsConceptIdRoute;
  DigDialogIdRoute: typeof DigDialogIdRoute;
  EvidenceConceptIdRoute: typeof EvidenceConceptIdRoute;
  ImportsJobIdRoute: typeof ImportsJobIdRoute;
  NotesBlockIdRoute: typeof NotesBlockIdRoute;
  ReviewWeeklyRoute: typeof ReviewWeeklyRoute;
  SessionSessionIdRoute: typeof SessionSessionIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_design': {
      id: '/_design';
      path: '/_design';
      fullPath: '/_design';
      preLoaderRoute: typeof DesignRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/ai': {
      id: '/ai';
      path: '/ai';
      fullPath: '/ai';
      preLoaderRoute: typeof AiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/curation': {
      id: '/curation';
      path: '/curation';
      fullPath: '/curation';
      preLoaderRoute: typeof CurationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/inbox': {
      id: '/inbox';
      path: '/inbox';
      fullPath: '/inbox';
      preLoaderRoute: typeof InboxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/map': {
      id: '/map';
      path: '/map';
      fullPath: '/map';
      preLoaderRoute: typeof MapRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/ops': {
      id: '/ops';
      path: '/ops';
      fullPath: '/ops';
      preLoaderRoute: typeof OpsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/season': {
      id: '/season';
      path: '/season';
      fullPath: '/season';
      preLoaderRoute: typeof SeasonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/artifacts/$runId': {
      id: '/artifacts/$runId';
      path: '/artifacts/$runId';
      fullPath: '/artifacts/$runId';
      preLoaderRoute: typeof ArtifactsRunIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/cases/$runId': {
      id: '/cases/$runId';
      path: '/cases/$runId';
      fullPath: '/cases/$runId';
      preLoaderRoute: typeof CasesRunIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/concepts/$conceptId': {
      id: '/concepts/$conceptId';
      path: '/concepts/$conceptId';
      fullPath: '/concepts/$conceptId';
      preLoaderRoute: typeof ConceptsConceptIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dig/$dialogId': {
      id: '/dig/$dialogId';
      path: '/dig/$dialogId';
      fullPath: '/dig/$dialogId';
      preLoaderRoute: typeof DigDialogIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/evidence/$conceptId': {
      id: '/evidence/$conceptId';
      path: '/evidence/$conceptId';
      fullPath: '/evidence/$conceptId';
      preLoaderRoute: typeof EvidenceConceptIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/imports/$jobId': {
      id: '/imports/$jobId';
      path: '/imports/$jobId';
      fullPath: '/imports/$jobId';
      preLoaderRoute: typeof ImportsJobIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/notes/$blockId': {
      id: '/notes/$blockId';
      path: '/notes/$blockId';
      fullPath: '/notes/$blockId';
      preLoaderRoute: typeof NotesBlockIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/review/weekly': {
      id: '/review/weekly';
      path: '/review/weekly';
      fullPath: '/review/weekly';
      preLoaderRoute: typeof ReviewWeeklyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/session/$sessionId': {
      id: '/session/$sessionId';
      path: '/session/$sessionId';
      fullPath: '/session/$sessionId';
      preLoaderRoute: typeof SessionSessionIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  AiRoute: AiRoute,
  CurationRoute: CurationRoute,
  InboxRoute: InboxRoute,
  MapRoute: MapRoute,
  OpsRoute: OpsRoute,
  SeasonRoute: SeasonRoute,
  SettingsRoute: SettingsRoute,
  ArtifactsRunIdRoute: ArtifactsRunIdRoute,
  CasesRunIdRoute: CasesRunIdRoute,
  ConceptsConceptIdRoute: ConceptsConceptIdRoute,
  DigDialogIdRoute: DigDialogIdRoute,
  EvidenceConceptIdRoute: EvidenceConceptIdRoute,
  ImportsJobIdRoute: ImportsJobIdRoute,
  NotesBlockIdRoute: NotesBlockIdRoute,
  ReviewWeeklyRoute: ReviewWeeklyRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
