// GENERATED by pnpm contracts:gen (packages/contracts/scripts/gen.ts) — DO NOT EDIT
import { AcquisitionImportStagedV1 } from './catalog/acquisition.js';
import {
  AiBudgetThresholdReachedV1,
  AiJobCompletedV1,
  AiJudgeDriftDetectedV1,
  AiModeChangedV1,
  AiProviderStatusChangedV1,
  AiWorkOrderApprovalRequestedV1,
  AiWorkOrderDecidedV1,
} from './catalog/ai.js';
import {
  CatalogConceptChangedV1,
  CatalogOverlayConflictedV1,
  CatalogPackActivatedV1,
} from './catalog/catalog.js';
import { GradingVerdictRevisedV1, Verdict } from './catalog/grading.js';
import { ItembankItemCorrectedV1 } from './catalog/itembank.js';
import {
  LearningDemandForecastedV1,
  LearningEvidenceRecordedV1,
  LearningLedgerMergedV1,
  LearningLevelPromotedV1,
  LearningMasteryChangedV1,
  LearningSessionCompletedV1,
} from './catalog/learning.js';
import { OpsBackupCompletedV1, OpsHealthChangedV1, OpsHostStateChangedV1 } from './catalog/ops.js';

export const EVENT_PAYLOADS = {
  'acquisition.import.staged': { 1: AcquisitionImportStagedV1 },
  'ai.budget.threshold_reached': { 1: AiBudgetThresholdReachedV1 },
  'ai.job.completed': { 1: AiJobCompletedV1 },
  'ai.judge.drift_detected': { 1: AiJudgeDriftDetectedV1 },
  'ai.mode.changed': { 1: AiModeChangedV1 },
  'ai.provider.status_changed': { 1: AiProviderStatusChangedV1 },
  'ai.work_order.approval_requested': { 1: AiWorkOrderApprovalRequestedV1 },
  'ai.work_order.decided': { 1: AiWorkOrderDecidedV1 },
  'catalog.concept.changed': { 1: CatalogConceptChangedV1 },
  'catalog.overlay.conflicted': { 1: CatalogOverlayConflictedV1 },
  'catalog.pack.activated': { 1: CatalogPackActivatedV1 },
  'grading.verdict.issued': { 1: Verdict },
  'grading.verdict.revised': { 1: GradingVerdictRevisedV1 },
  'itembank.item.corrected': { 1: ItembankItemCorrectedV1 },
  'learning.demand.forecasted': { 1: LearningDemandForecastedV1 },
  'learning.evidence.recorded': { 1: LearningEvidenceRecordedV1 },
  'learning.ledger.merged': { 1: LearningLedgerMergedV1 },
  'learning.level.promoted': { 1: LearningLevelPromotedV1 },
  'learning.mastery.changed': { 1: LearningMasteryChangedV1 },
  'learning.session.completed': { 1: LearningSessionCompletedV1 },
  'ops.backup.completed': { 1: OpsBackupCompletedV1 },
  'ops.health.changed': { 1: OpsHealthChangedV1 },
  'ops.host_state.changed': { 1: OpsHostStateChangedV1 },
} as const;

export const EVENT_META = {
  'acquisition.import.staged': { ifId: 'IF-EV-04', producer: 'content', freeze: 'O', slice: 'R2' },
  'ai.budget.threshold_reached': { ifId: 'IF-EV-19', producer: 'ai-gateway', freeze: 'O', slice: 'R2' },
  'ai.job.completed': { ifId: 'IF-EV-16', producer: 'ai-gateway', freeze: 'O', slice: 'R2' },
  'ai.judge.drift_detected': { ifId: 'IF-EV-20', producer: 'ai-gateway', freeze: 'O', slice: 'R2' },
  'ai.mode.changed': { ifId: 'IF-EV-14', producer: 'ai-gateway', freeze: 'D', slice: 'R0' },
  'ai.provider.status_changed': { ifId: 'IF-EV-15', producer: 'ai-gateway', freeze: 'O', slice: 'R2' },
  'ai.work_order.approval_requested': { ifId: 'IF-EV-17', producer: 'ai-gateway', freeze: 'O', slice: 'R2' },
  'ai.work_order.decided': { ifId: 'IF-EV-18', producer: 'ai-gateway', freeze: 'O', slice: 'R2' },
  'catalog.concept.changed': { ifId: 'IF-EV-02', producer: 'content', freeze: 'D', slice: 'R0' },
  'catalog.overlay.conflicted': { ifId: 'IF-EV-03', producer: 'content', freeze: 'O', slice: 'R2' },
  'catalog.pack.activated': { ifId: 'IF-EV-01', producer: 'content', freeze: 'D', slice: 'R0' },
  'grading.verdict.issued': { ifId: 'IF-EV-05', producer: 'content', freeze: 'D', slice: 'R0' },
  'grading.verdict.revised': { ifId: 'IF-EV-06', producer: 'content', freeze: 'O', slice: 'R2' },
  'itembank.item.corrected': { ifId: 'IF-EV-07', producer: 'content', freeze: 'D', slice: 'R1' },
  'learning.demand.forecasted': { ifId: 'IF-EV-10', producer: 'learning', freeze: 'D', slice: 'R1' },
  'learning.evidence.recorded': { ifId: 'IF-EV-08', producer: 'learning', freeze: 'D', slice: 'R0' },
  'learning.ledger.merged': { ifId: 'IF-EV-13', producer: 'learning', freeze: 'D', slice: 'R1' },
  'learning.level.promoted': { ifId: 'IF-EV-12', producer: 'learning', freeze: 'D', slice: 'R1' },
  'learning.mastery.changed': { ifId: 'IF-EV-11', producer: 'learning', freeze: 'D', slice: 'R1' },
  'learning.session.completed': { ifId: 'IF-EV-09', producer: 'learning', freeze: 'D', slice: 'R0' },
  'ops.backup.completed': { ifId: 'IF-EV-22', producer: 'ops-api', freeze: 'D', slice: 'R1' },
  'ops.health.changed': { ifId: 'IF-EV-21', producer: 'ops-api', freeze: 'D', slice: 'R0' },
  'ops.host_state.changed': { ifId: 'IF-EV-23', producer: 'ops-api', freeze: 'D', slice: 'R1' },
} as const;

export type IntegrationEventType = keyof typeof EVENT_PAYLOADS;

export const CONTRACTS_HASH = 'a60a68185f091857bcf15667ec9f29dd13b2bde39e85a919355a3ffd2bf21335';
