// GENERATED by pnpm contracts:gen (packages/contracts/scripts/gen.ts) — DO NOT EDIT

export const ROUTING = {
  'ai-gateway': {
    content: { mode: 'durable', types: ['ai.job.completed', 'ai.mode.changed', 'ai.work_order.decided'] },
    gateway: { mode: 'notify', types: ['ai.budget.threshold_reached', 'ai.judge.drift_detected', 'ai.mode.changed', 'ai.provider.status_changed', 'ai.work_order.approval_requested', 'ai.work_order.decided'] },
    learning: { mode: 'durable', types: ['ai.mode.changed'] },
    'ops-api': { mode: 'durable', types: ['ai.budget.threshold_reached', 'ai.judge.drift_detected', 'ai.mode.changed', 'ai.provider.status_changed'] },
  },
  content: {
    gateway: { mode: 'notify', types: ['acquisition.import.staged', 'catalog.overlay.conflicted', 'catalog.pack.activated', 'grading.verdict.revised', 'itembank.item.corrected'] },
    learning: { mode: 'durable', types: ['catalog.concept.changed', 'catalog.pack.activated', 'grading.verdict.issued', 'grading.verdict.revised', 'itembank.item.corrected'] },
  },
  learning: {
    content: { mode: 'durable', types: ['learning.demand.forecasted', 'learning.evidence.recorded', 'learning.session.completed'] },
    gateway: { mode: 'notify', types: ['learning.ledger.merged', 'learning.level.promoted', 'learning.mastery.changed', 'learning.session.completed'] },
    'ops-api': { mode: 'durable', types: ['learning.ledger.merged', 'learning.level.promoted', 'learning.session.completed'] },
  },
  'ops-api': {
    'ai-gateway': { mode: 'durable', types: ['ops.host_state.changed'] },
    gateway: { mode: 'notify', types: ['ops.backup.completed', 'ops.health.changed'] },
    learning: { mode: 'durable', types: ['ops.host_state.changed'] },
  },
} as const;

export const SUBSCRIPTIONS = {
  'ai-gateway': {
    'ops.host_state.changed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['idle_window_open', 'power', 'interactive_cli', 'sampled_at'] },
  },
  content: {
    'ai.job.completed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['job_id', 'task_id', 'work_order_id', 'outcome', 'result_ref', 'prompt_version'] },
    'ai.mode.changed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['mode', 'changed_at'] },
    'ai.work_order.decided': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['work_order_id', 'decision', 'reservation'] },
    'learning.demand.forecasted': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['window_days', 'demand', 'computed_at'] },
    'learning.evidence.recorded': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['ledger_event_id', 'verdict_id', 'item_id', 'format', 'result', 'latency_ms', 'rapid', 'confidence', 'selected_option_key', 'recorded_at', 'phase', 'item_beta_after'] },
    'learning.session.completed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['session_id', 'modes', 'completed_at'] },
  },
  gateway: {
    'acquisition.import.staged': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ai.budget.threshold_reached': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ai.judge.drift_detected': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ai.mode.changed': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ai.provider.status_changed': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ai.work_order.approval_requested': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ai.work_order.decided': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'catalog.overlay.conflicted': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'catalog.pack.activated': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'grading.verdict.revised': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'itembank.item.corrected': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'learning.ledger.merged': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'learning.level.promoted': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'learning.mastery.changed': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'learning.session.completed': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ops.backup.completed': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
    'ops.health.changed': { mode: 'notify', on_poison: 'drop', schema_versions: [1], reads: ['*'] },
  },
  learning: {
    'ai.mode.changed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['mode', 'providers', 'changed_at'] },
    'catalog.concept.changed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['change', 'concept', 'version'] },
    'catalog.pack.activated': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['pack_id', 'track', 'version', 'manifest_hash', 'changed_concept_ids', 'offline_cap_level', 'catalog_version'] },
    'grading.verdict.issued': { mode: 'durable', on_poison: 'halt', schema_versions: [1], reads: ['verdict_id', 'attempt_id', 'session_id', 'block_id', 'item_id', 'item_content_hash', 'item_beta_snapshot', 'item_n_options', 'gate_result_id', 'stakes', 'concept_id', 'ku_ids', 'mc_ids', 'facet', 'format', 'response_mode', 'tier', 'result', 'band', 'score', 'confidence', 'latency_ms', 'rapid', 'hints_used', 'grader_engine', 'calibrated', 'grader_confidence', 'pending', 'provisional', 'w_format', 'w_grader', 'gaming_factor', 'recommended_grade', 'ai_mode', 'content_policy_version', 'judge_log_ref', 'prompt_version', 'issued_at'] },
    'grading.verdict.revised': { mode: 'durable', on_poison: 'halt', schema_versions: [1], reads: ['verdict', 'supersedes_verdict_id', 'reason', 'band_changed'] },
    'itembank.item.corrected': { mode: 'durable', on_poison: 'halt', schema_versions: [1], reads: ['item_id', 'correction', 'evidence_policy', 'basis', 'gate_result_id', 'effective_from'] },
    'ops.host_state.changed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['idle_window_open', 'power', 'sampled_at'] },
  },
  'ops-api': {
    'ai.budget.threshold_reached': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['scope', 'provider_id', 'ratio', 'period'] },
    'ai.judge.drift_detected': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['provider_id', 'task_id', 'model_version_new'] },
    'ai.mode.changed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['mode', 'previous_mode', 'reasons', 'changed_at'] },
    'ai.provider.status_changed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['provider_id', 'status', 'breaker'] },
    'learning.ledger.merged': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['checkpoint_id', 'imported_events'] },
    'learning.level.promoted': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['track', 'to_level', 'provisional'] },
    'learning.session.completed': { mode: 'durable', on_poison: 'dead_letter', schema_versions: [1], reads: ['session_id', 'duration_ms', 'first_item_latency_ms', 'completed_at'] },
  },
} as const;
