// 테스트 전용 .fpack bundle 레코드 18종 유효 샘플(무네트워크).
export const ULID = '01HZX3Y5K7M9N2P4Q6R8S0T1V2';
export const SHA = 'a'.repeat(64);
const H = { content_hash: SHA };
const ext = {};

export const sourceRef = {
  source_id: 'src.k8s-docs',
  locator: 'concepts/probes',
  section: 'Liveness probes',
  usage: 'link_only',
  retrieved_at: '2026-01-15',
  product_version: null,
  quote: null,
};

export const records = {
  track: {
    kind: 'track',
    track_id: 'k8s',
    name_ko: '쿠버네티스',
    name_en: 'Kubernetes',
    track_group: 'infra',
    sort_order: 1,
    offline_cap_level: 3,
    oracle_cap_level: 4,
    summary_ko: '컨테이너 오케스트레이션',
    ext,
    ...H,
  },
  concept: {
    kind: 'concept',
    concept_id: 'k8s.probes',
    track_id: 'k8s',
    level: 2,
    knowledge_type: 'C',
    tier: 'A',
    title_ko: '프로브',
    title_en: 'Probes',
    summary_ko: '컨테이너 상태 점검',
    aliases: [],
    tags: [],
    volatility: 'stable',
    required_for_level: 2,
    deprecated_by: null,
    theory_md: '이론',
    code_md: '코드',
    core_md: '핵심',
    diagrams: {
      flow01: {
        mermaid: 'graph TD; A-->B',
        alt: '프로브 흐름도',
        summary: '프로브가 컨테이너 상태를 점검하고 실패하면 재시작하는 흐름을 보여 준다.',
      },
    },
    sources: [sourceRef],
    ext,
    ...H,
  },
  edge: { kind: 'edge', from_concept_id: 'k8s.pods', to_concept_id: 'k8s.probes', edge_kind: 'prereq', weight: 1 },
  alias: { kind: 'alias', entity_kind: 'concept', alias_id: 'health-check', target_id: 'k8s.probes' },
  ku: {
    kind: 'ku',
    ku_id: 'k8s.probes.k01',
    concept_id: 'k8s.probes',
    statement: 'liveness probe가 실패하면 kubelet이 컨테이너를 재시작한다.',
    facet: 'concept',
    scope: '',
    vol: 'stable',
    valid_as_of: null,
    deprecated_by: null,
    source_refs: [sourceRef],
    trust: 'authored',
    origin: 'authored',
    status: 'published',
    ext,
    ...H,
  },
  misconception: {
    kind: 'misconception',
    mc_id: 'k8s.probes.m01',
    concept_id: 'k8s.probes',
    statement: 'readiness 실패도 컨테이너를 재시작한다고 믿는다.',
    correction: 'readiness 실패는 트래픽만 끊고 재시작하지 않는다.',
    meta_family: 'mf_cause',
    related_ku_ids: ['k8s.probes.k01'],
    status: 'active',
    ext,
    ...H,
  },
  source: {
    kind: 'source',
    source_id: 'src.k8s-docs',
    source_type: 'doc',
    title: 'Kubernetes 공식 문서',
    url: null,
    ref_text: null,
    license_grade: 'A',
    fetched_at: null,
    ext,
    ...H,
  },
  rubric: {
    kind: 'rubric',
    rubric_id: 'rb.feynman-teach',
    dims: { dims: { dim01: { name: '정확성', weight: 0.5, levels: { l0: '없음', l3: '충분' } } } },
    ext,
    ...H,
  },
  case: {
    kind: 'case',
    case_id: 'k8s.case.liveness-restart-storm',
    track_id: 'k8s',
    level: 4,
    case_kind: 'incident',
    title_ko: '재시작 폭풍',
    spec: { situation_md: '상황' },
    variant_params: {},
    root_cause_pool: {},
    best_if: { node01: { rules: {}, default_best: 'opt_a' } },
    contested: false,
    rubric_id: 'rb.feynman-teach',
    debrief_md: '복기',
    inspired_by: null,
    primary_sources: [],
    ext,
    ...H,
  },
  artifact: {
    kind: 'artifact',
    artifact_id: 'sre.art.postmortem-cascading-latency',
    track_id: 'sre',
    level: 4,
    artifact_kind: 'postmortem',
    title_ko: '포스트모템',
    template_md: '# 템플릿',
    rubric_id: 'rb.feynman-teach',
    rebuttal_bank: {},
    model_answer_md: '모범',
    primary_sources: [],
    ext,
    ...H,
  },
  lab: {
    kind: 'lab',
    lab_id: 'docker.lab.dockerfile-faded',
    track_id: 'docker',
    level: 2,
    lab_kind: 'code',
    language: 'js',
    task_md: '과제',
    starter_code: '',
    public_tests: '',
    hidden_tests: '',
    complexity: null,
    oracle_log_sha256: null,
    ext,
    ...H,
  },
  blueprint: {
    kind: 'blueprint',
    blueprint_id: 'cert-cka@2026',
    exam: 'CKA',
    edition: '2026',
    source_url: 'https://example.com/cka',
    source_edition: '2026-01',
    title_ko: 'CKA 청사진',
    ext,
    ...H,
  },
  blueprint_item: {
    kind: 'blueprint_item',
    blueprint_id: 'cert-cka@2026',
    section_key: 's1',
    parent_key: null,
    title_ko: '클러스터 아키텍처',
    weight: 0.2,
  },
  blueprint_map: {
    kind: 'blueprint_map',
    blueprint_id: 'cert-cka@2026',
    section_key: 's1_2',
    concept_id: 'k8s.probes',
    weight: 1,
  },
  path: {
    kind: 'path',
    path_id: 'path.backend-core',
    title_ko: '백엔드 코어',
    description_ko: '핵심 경로',
    tracks: ['be'],
    concept_ids: ['k8s.probes'],
    ...H,
  },
  item_model: {
    kind: 'item_model',
    model_id: 'k8s.probes.im01',
    origin: 'pack',
    concept_id: 'k8s.probes',
    format: 'mcq',
    ku_ids: ['k8s.probes.k01'],
    slots: {},
    constraints: null,
    metamorphic: {},
    stem_family: 'sf_probe',
    status: 'active',
    author: 'seed',
    prompt_version: null,
    sample_gate: {},
    ext,
    ...H,
  },
  item: {
    kind: 'item',
    item_id: 'k8s.probes.i01',
    origin: 'pack',
    model_id: null,
    family_id: 'fam01',
    concept_id: 'k8s.probes',
    ku_ids: ['k8s.probes.k01'],
    mc_ids: [],
    facet: 'concept',
    format: 'mcq',
    response_mode: 'recognition',
    level: 2,
    bloom: 'apply',
    stakes: 'S0',
    tier: 'A',
    n_options: 4,
    beta_prior: 0,
    stem: {},
    options: {},
    answer_key: 'opt_a',
    explanation_md: '해설',
    distractor_mc: {},
    lab_id: null,
    source_kind: 'seed',
    stem_family: 'sf_probe',
    gate_status: 'seed_reviewed',
    defect_manifest: null,
    s2_mode: null,
    lineage: {},
    snapshot: {},
    ext,
    ...H,
  },
  gate_result: {
    kind: 'gate_result',
    gate_result_id: ULID,
    subject_kind: 'item',
    subject_id: 'k8s.probes.i01',
    content_hash: SHA,
    gate: 'G3',
    engine: 'D',
    provider_id: null,
    run_context: 'seed_build',
    pass: true,
    score: null,
    probabilities: null,
    detail: {},
  },
} as const;
