import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { CONTRACTS_HASH } from '@fathom/contracts/events/registry.gen';
import { APP_ROOT } from '@fathom/testkit/spawn-stack';
import { describe, expect, it } from 'vitest';

// CT-SYS-006 — contracts:gen 생성물이 원천과 같다(TST-01 §6.5). web routeTree.gen.ts는 범위 밖(T-00-14 단위 테스트 몫).

const HEADER = '// GENERATED by pnpm contracts:gen (packages/contracts/scripts/gen.ts) — DO NOT EDIT';

describe('교차 계약: 생성물 최신성', () => {
  it('CT-SYS-006 contracts:gen --check가 stale 0으로 통과하고 생성 파일 머리 주석·CONTRACTS_HASH 형식이 맞다 [NFR-MAINT-006]', () => {
    // Arrange / Act
    const run = spawnSync(
      process.execPath,
      [
        '--disable-warning=ExperimentalWarning',
        '--import',
        'tsx',
        '--conditions=source',
        'packages/contracts/scripts/gen.ts',
        '--check',
      ],
      {
        cwd: APP_ROOT,
        env: { PATH: process.env.PATH ?? '', HOME: process.env.HOME ?? '' },
        encoding: 'utf8',
        timeout: 120_000,
      },
    );
    // Assert
    expect(run.status, `${run.stdout}\n${run.stderr}`).toBe(0);
    expect(`${run.stdout}${run.stderr}`).not.toContain('stale');
    for (const name of ['registry.gen.ts', 'routing.gen.ts']) {
      const first = readFileSync(path.join(APP_ROOT, 'packages', 'contracts', 'src', 'events', name), 'utf8').split(
        '\n',
      )[0];
      expect(first, name).toBe(HEADER);
    }
    expect(CONTRACTS_HASH).toMatch(/^[0-9a-f]{64}$/);
  });
});
