// IF-01 §4 표 9개 179행(IF-GW-001은 §4.2·§4.9 중복 → 1회) — 문서에서 뽑은 기대 표(Brief §4.3).
// [IF-ID, 메서드, 경로, route id, 멱등, 데드라인(null = 생략), 페이지]
export type ExpectedRow = readonly [string, string, string, string, boolean, number | null, boolean];
export const EXPECTED_GW_ROUTES: readonly ExpectedRow[] = [
  ['IF-GW-001', 'POST', '/api/v1/cli/bootstrap-token', 'gateway.cli.bootstrap_token', true, null, false],
  ['IF-GW-002', 'POST', '/api/v1/session/exchange', 'gateway.session.exchange', false, null, false],
  ['IF-GW-003', 'GET', '/api/v1/session/csrf', 'gateway.session.csrf', false, null, false],
  ['IF-GW-004', 'POST', '/api/v1/session/logout', 'gateway.session.logout', true, null, false],
  ['IF-GW-005', 'GET', '/api/v1/stream', 'gateway.stream.open', false, null, false],
  ['IF-GW-006', 'GET', '/api/v1/session', 'gateway.session.status', false, null, false],
  ['IF-GW-010', 'GET', '/api/v1/home', 'gateway.home.get', false, 1500, false],
  ['IF-GW-011', 'GET', '/api/v1/home/forecast', 'gateway.home.forecast', false, null, false],
  ['IF-GW-015', 'POST', '/api/v1/sessions', 'gateway.sessions.create', true, 2000, false],
  ['IF-GW-016', 'GET', '/api/v1/sessions/active', 'gateway.sessions.active', false, null, false],
  ['IF-GW-017', 'GET', '/api/v1/sessions/{session_id}', 'gateway.sessions.get', false, null, false],
  ['IF-GW-018', 'GET', '/api/v1/sessions/{session_id}/blocks/{block_id}', 'gateway.sessions.block', false, null, false],
  [
    'IF-GW-019',
    'GET',
    '/api/v1/sessions/{session_id}/blocks/{block_id}/alternatives',
    'gateway.sessions.block_alternatives',
    false,
    null,
    false,
  ],
  [
    'IF-GW-020',
    'POST',
    '/api/v1/sessions/{session_id}/attempts',
    'gateway.sessions.attempts.submit',
    true,
    2900,
    false,
  ],
  [
    'IF-GW-021',
    'POST',
    '/api/v1/sessions/{session_id}/attempts/{attempt_id}/self-grade',
    'gateway.sessions.attempts.self_grade',
    true,
    2900,
    false,
  ],
  [
    'IF-GW-022',
    'POST',
    '/api/v1/sessions/{session_id}/blocks/{block_id}:swap',
    'gateway.sessions.block_swap',
    true,
    null,
    false,
  ],
  [
    'IF-GW-023',
    'POST',
    '/api/v1/sessions/{session_id}/blocks/{block_id}:skip',
    'gateway.sessions.block_skip',
    true,
    null,
    false,
  ],
  [
    'IF-GW-024',
    'POST',
    '/api/v1/sessions/{session_id}/blocks/{block_id}:lock',
    'gateway.sessions.block_lock',
    true,
    null,
    false,
  ],
  [
    'IF-GW-025',
    'POST',
    '/api/v1/sessions/{session_id}/blocks/{block_id}:complete',
    'gateway.sessions.block_complete',
    true,
    null,
    false,
  ],
  ['IF-GW-026', 'POST', '/api/v1/sessions/{session_id}:pause', 'gateway.sessions.pause', true, null, false],
  ['IF-GW-027', 'POST', '/api/v1/sessions/{session_id}:resume', 'gateway.sessions.resume', true, null, false],
  ['IF-GW-028', 'POST', '/api/v1/sessions/{session_id}:complete', 'gateway.sessions.complete', true, null, false],
  ['IF-GW-029', 'POST', '/api/v1/sessions/{session_id}:abandon', 'gateway.sessions.abandon', true, null, false],
  ['IF-GW-030', 'GET', '/api/v1/sessions/{session_id}/report', 'gateway.sessions.report', false, null, false],
  [
    'IF-GW-031',
    'POST',
    '/api/v1/sessions/{session_id}/self-assessments',
    'gateway.sessions.self_assessments',
    true,
    null,
    false,
  ],
  ['IF-GW-032', 'GET', '/api/v1/items/{item_id}/hints/{step}', 'gateway.items.hint', false, null, false],
  ['IF-GW-033', 'POST', '/api/v1/items/{item_id}/reports', 'gateway.items.report', true, null, false],
  [
    'IF-GW-034',
    'POST',
    '/api/v1/evidence/events/{ledger_event_id}:confirm-rating',
    'gateway.evidence.confirm_rating',
    true,
    null,
    false,
  ],
  ['IF-GW-035', 'GET', '/api/v1/verdicts/{verdict_id}', 'gateway.verdicts.get', false, null, false],
  ['IF-GW-036', 'POST', '/api/v1/verdicts/{verdict_id}/appeals', 'gateway.verdicts.appeal', true, null, false],
  ['IF-GW-037', 'GET', '/api/v1/appeals/{appeal_id}', 'gateway.appeals.get', false, null, false],
  ['IF-GW-038', 'POST', '/api/v1/labs/runs', 'gateway.labs.run', true, 6000, false],
  ['IF-GW-039', 'GET', '/api/v1/labs/platform', 'gateway.labs.platform', false, null, false],
  ['IF-GW-040', 'GET', '/api/v1/tracks', 'gateway.tracks.list', false, null, false],
  ['IF-GW-041', 'GET', '/api/v1/tracks/{track}', 'gateway.tracks.get', false, null, false],
  ['IF-GW-042', 'GET', '/api/v1/paths', 'gateway.paths.list', false, null, false],
  ['IF-GW-043', 'GET', '/api/v1/concepts/{concept_id}', 'gateway.concepts.get', false, null, false],
  ['IF-GW-044', 'GET', '/api/v1/concepts/{concept_id}/neighbors', 'gateway.concepts.neighbors', false, null, false],
  ['IF-GW-045', 'GET', '/api/v1/concepts/{concept_id}/sources', 'gateway.concepts.sources', false, null, false],
  ['IF-GW-046', 'GET', '/api/v1/overlays', 'gateway.overlays.list', false, null, true],
  ['IF-GW-047', 'POST', '/api/v1/overlays', 'gateway.overlays.create', true, null, false],
  ['IF-GW-048', 'POST', '/api/v1/overlays/{patch_id}:revert', 'gateway.overlays.revert', true, null, false],
  [
    'IF-GW-049',
    'POST',
    '/api/v1/concepts/{concept_id}/outdated-reports',
    'gateway.concepts.outdated_report',
    true,
    null,
    false,
  ],
  ['IF-GW-050', 'GET', '/api/v1/search', 'gateway.search.query', false, 1000, false],
  ['IF-GW-051', 'GET', '/api/v1/promotion/{track}', 'gateway.promotion.get', false, null, false],
  ['IF-GW-052', 'GET', '/api/v1/blueprints', 'gateway.blueprints.list', false, null, false],
  ['IF-GW-053', 'POST', '/api/v1/blueprints:import', 'gateway.blueprints.import', true, null, false],
  ['IF-GW-055', 'GET', '/api/v1/map', 'gateway.map.get', false, 1500, false],
  ['IF-GW-056', 'GET', '/api/v1/evidence/{concept_id}', 'gateway.evidence.get', false, null, false],
  ['IF-GW-057', 'GET', '/api/v1/evidence/{concept_id}/events', 'gateway.evidence.events', false, null, true],
  ['IF-GW-060', 'POST', '/api/v1/dialogs', 'gateway.dialogs.create', true, null, false],
  ['IF-GW-061', 'GET', '/api/v1/dialogs/{dialog_id}', 'gateway.dialogs.get', false, null, false],
  ['IF-GW-062', 'POST', '/api/v1/dialogs/{dialog_id}/turns', 'gateway.dialogs.turn', true, 3500, false],
  [
    'IF-GW-063',
    'GET',
    '/api/v1/dialogs/{dialog_id}/turns/{turn_id}/utterance',
    'gateway.dialogs.utterance',
    false,
    60000,
    false,
  ],
  ['IF-GW-064', 'POST', '/api/v1/dialogs/{dialog_id}:end', 'gateway.dialogs.end', true, null, false],
  ['IF-GW-065', 'GET', '/api/v1/notes/{block_id}', 'gateway.notes.get', false, null, false],
  ['IF-GW-066', 'PUT', '/api/v1/notes/{block_id}/draft', 'gateway.notes.draft', true, null, false],
  [
    'IF-GW-067',
    'GET',
    '/api/v1/verdicts/{verdict_id}/feedback',
    'gateway.verdicts.feedback_stream',
    false,
    60000,
    false,
  ],
  ['IF-GW-068', 'POST', '/api/v1/cases/runs', 'gateway.cases.start', true, null, false],
  ['IF-GW-069', 'GET', '/api/v1/cases/runs/{run_id}', 'gateway.cases.get', false, null, false],
  ['IF-GW-070', 'GET', '/api/v1/cases', 'gateway.cases.list', false, null, false],
  ['IF-GW-071', 'POST', '/api/v1/artifacts/runs', 'gateway.artifacts.start', true, null, false],
  ['IF-GW-072', 'GET', '/api/v1/artifacts/runs/{run_id}', 'gateway.artifacts.get', false, null, false],
  ['IF-GW-073', 'PUT', '/api/v1/artifacts/runs/{run_id}/draft', 'gateway.artifacts.draft', true, null, false],
  ['IF-GW-074', 'POST', '/api/v1/artifacts/runs/{run_id}:rebut', 'gateway.artifacts.rebut', true, null, false],
  ['IF-GW-075', 'GET', '/api/v1/review/weekly', 'gateway.review.weekly', false, null, false],
  ['IF-GW-076', 'POST', '/api/v1/review/weekly/{week}:complete', 'gateway.review.weekly_complete', true, null, false],
  ['IF-GW-077', 'GET', '/api/v1/review/calibration', 'gateway.review.calibration', false, null, false],
  ['IF-GW-078', 'GET', '/api/v1/season', 'gateway.season.get', false, null, false],
  ['IF-GW-079', 'POST', '/api/v1/season', 'gateway.season.create', true, null, false],
  ['IF-GW-080', 'POST', '/api/v1/season/{season_id}:close', 'gateway.season.close', true, null, false],
  ['IF-GW-081', 'GET', '/api/v1/review/radar', 'gateway.review.radar', false, null, false],
  ['IF-GW-082', 'GET', '/api/v1/review/portfolio', 'gateway.review.portfolio', false, null, false],
  ['IF-GW-083', 'POST', '/api/v1/cases/runs/{run_id}/evidence-requests', 'gateway.cases.evidence', true, null, false],
  ['IF-GW-084', 'POST', '/api/v1/cases/runs/{run_id}/attempts', 'gateway.cases.attempt', true, 2900, false],
  ['IF-GW-085', 'GET', '/api/v1/inbox', 'gateway.inbox.list', false, null, true],
  ['IF-GW-086', 'POST', '/api/v1/inbox', 'gateway.inbox.capture', true, null, false],
  ['IF-GW-087', 'POST', '/api/v1/inbox/{inbox_id}:triage', 'gateway.inbox.triage', true, null, false],
  ['IF-GW-088', 'POST', '/api/v1/imports', 'gateway.imports.create', true, null, false],
  ['IF-GW-089', 'GET', '/api/v1/imports', 'gateway.imports.list', false, null, true],
  ['IF-GW-090', 'GET', '/api/v1/imports/{job_id}', 'gateway.imports.get', false, null, false],
  ['IF-GW-091', 'GET', '/api/v1/imports/{job_id}/diff', 'gateway.imports.diff', false, null, true],
  ['IF-GW-092', 'POST', '/api/v1/imports/{job_id}:approve', 'gateway.imports.approve', true, null, false],
  ['IF-GW-093', 'POST', '/api/v1/imports/{job_id}:reject', 'gateway.imports.reject', true, null, false],
  ['IF-GW-094', 'POST', '/api/v1/imports/{job_id}:resume', 'gateway.imports.resume', true, null, false],
  ['IF-GW-095', 'GET', '/api/v1/curation/reports', 'gateway.curation.reports', false, null, true],
  [
    'IF-GW-096',
    'POST',
    '/api/v1/curation/reports/{report_id}:resolve',
    'gateway.curation.report_resolve',
    true,
    null,
    false,
  ],
  ['IF-GW-097', 'GET', '/api/v1/curation/item-health', 'gateway.curation.item_health', false, null, true],
  ['IF-GW-098', 'GET', '/api/v1/curation/pending', 'gateway.curation.pending', false, null, true],
  ['IF-GW-099', 'GET', '/api/v1/curation/conflicts', 'gateway.curation.conflicts', false, null, true],
  [
    'IF-GW-100',
    'POST',
    '/api/v1/curation/conflicts/{conflict_id}:resolve',
    'gateway.curation.conflict_resolve',
    true,
    null,
    false,
  ],
  [
    'IF-GW-101',
    'POST',
    '/api/v1/curation/items/{item_id}:quarantine',
    'gateway.curation.item_quarantine',
    true,
    null,
    false,
  ],
  ['IF-GW-102', 'GET', '/api/v1/curation/warming', 'gateway.curation.warming', false, null, false],
  ['IF-GW-103', 'POST', '/api/v1/artifacts/runs/{run_id}:submit', 'gateway.artifacts.submit', true, 2900, false],
  ['IF-GW-104', 'GET', '/api/v1/curation/staging', 'gateway.curation.staging', false, null, true],
  ['IF-GW-105', 'GET', '/api/v1/ai/status', 'gateway.ai.status', false, null, false],
  ['IF-GW-106', 'POST', '/api/v1/ai/providers:probe', 'gateway.ai.probe', true, null, false],
  ['IF-GW-107', 'PUT', '/api/v1/ai/providers/{provider_id}/consent', 'gateway.ai.consent', true, null, false],
  ['IF-GW-108', 'PUT', '/api/v1/ai/providers/{provider_id}/config', 'gateway.ai.provider_config', true, null, false],
  ['IF-GW-109', 'POST', '/api/v1/ai/providers/generic-cli', 'gateway.ai.generic_cli_add', true, null, false],
  [
    'IF-GW-110',
    'DELETE',
    '/api/v1/ai/providers/generic-cli/{provider_id}',
    'gateway.ai.generic_cli_remove',
    true,
    null,
    false,
  ],
  ['IF-GW-111', 'PUT', '/api/v1/ai/secrets/{provider_id}', 'gateway.ai.secret_put', true, null, false],
  ['IF-GW-112', 'GET', '/api/v1/ai/secrets', 'gateway.ai.secrets', false, null, false],
  ['IF-GW-113', 'DELETE', '/api/v1/ai/secrets/{provider_id}', 'gateway.ai.secret_delete', true, null, false],
  ['IF-GW-114', 'POST', '/api/v1/ai/secrets:unlock', 'gateway.ai.secrets_unlock', true, null, false],
  ['IF-GW-115', 'GET', '/api/v1/ai/usage', 'gateway.ai.usage', false, null, false],
  ['IF-GW-116', 'GET', '/api/v1/ai/calls', 'gateway.ai.calls', false, null, true],
  ['IF-GW-117', 'GET', '/api/v1/ai/budget', 'gateway.ai.budget', false, null, false],
  ['IF-GW-118', 'PUT', '/api/v1/ai/budget', 'gateway.ai.budget_put', true, null, false],
  ['IF-GW-119', 'GET', '/api/v1/ai/preferences', 'gateway.ai.preferences', false, null, false],
  ['IF-GW-120', 'PUT', '/api/v1/ai/preferences', 'gateway.ai.preferences_put', true, null, false],
  ['IF-GW-121', 'GET', '/api/v1/ai/work-orders', 'gateway.ai.work_orders', false, null, true],
  [
    'IF-GW-122',
    'POST',
    '/api/v1/ai/work-orders/{work_order_id}:decide',
    'gateway.ai.work_order_decide',
    true,
    null,
    false,
  ],
  ['IF-GW-123', 'GET', '/api/v1/ai/jobs', 'gateway.ai.jobs', false, null, true],
  ['IF-GW-124', 'POST', '/api/v1/ai/jobs/{job_id}:cancel', 'gateway.ai.job_cancel', true, null, false],
  ['IF-GW-125', 'GET', '/api/v1/ai/calibration', 'gateway.ai.calibration', false, null, false],
  ['IF-GW-126', 'GET', '/api/v1/ai/calibration/confirm-cards', 'gateway.ai.confirm_cards', false, null, false],
  ['IF-GW-127', 'POST', '/api/v1/ai/calibration/gold/{gold_id}:confirm', 'gateway.ai.gold_confirm', true, null, false],
  ['IF-GW-128', 'POST', '/api/v1/ai/calibration:run', 'gateway.ai.calibration_run', true, null, false],
  ['IF-GW-129', 'GET', '/api/v1/ai/firewall/patterns', 'gateway.ai.firewall_patterns', false, null, false],
  ['IF-GW-130', 'PUT', '/api/v1/ai/firewall/patterns', 'gateway.ai.firewall_patterns_put', true, null, false],
  ['IF-GW-131', 'GET', '/api/v1/ai/firewall/log', 'gateway.ai.firewall_log', false, null, true],
  ['IF-GW-132', 'POST', '/api/v1/ai/firewall:preview', 'gateway.ai.firewall_preview', false, null, false],
  [
    'IF-GW-133',
    'POST',
    '/api/v1/curation/staging/{staging_id}:approve',
    'gateway.curation.staging_approve',
    true,
    null,
    false,
  ],
  ['IF-GW-135', 'GET', '/api/v1/ops/health', 'gateway.ops.health', false, null, false],
  ['IF-GW-136', 'POST', '/api/v1/ops/banners/{banner_id}:dismiss', 'gateway.ops.banner_dismiss', true, null, false],
  ['IF-GW-137', 'GET', '/api/v1/ops/operations/{op_id}', 'gateway.ops.operation', false, null, false],
  ['IF-GW-138', 'GET', '/api/v1/ops/operations', 'gateway.ops.operations', false, null, true],
  ['IF-GW-139', 'POST', '/api/v1/ops/backups', 'gateway.ops.backup_run', true, null, false],
  ['IF-GW-140', 'GET', '/api/v1/ops/backups', 'gateway.ops.backups', false, null, true],
  ['IF-GW-141', 'POST', '/api/v1/ops/restores', 'gateway.ops.restore', true, null, false],
  ['IF-GW-142', 'GET', '/api/v1/ops/backups/secondary', 'gateway.ops.secondary', false, null, false],
  ['IF-GW-143', 'PUT', '/api/v1/ops/backups/secondary', 'gateway.ops.secondary_put', true, null, false],
  ['IF-GW-144', 'POST', '/api/v1/ops/backups/secondary:unlock', 'gateway.ops.secondary_unlock', true, null, false],
  ['IF-GW-145', 'POST', '/api/v1/ops/exports', 'gateway.ops.export', true, null, false],
  ['IF-GW-146', 'POST', '/api/v1/ops/imports', 'gateway.ops.import', true, null, false],
  ['IF-GW-147', 'GET', '/api/v1/ops/doctor', 'gateway.ops.doctor', false, null, false],
  ['IF-GW-148', 'POST', '/api/v1/ops/doctor:run', 'gateway.ops.doctor_run', true, null, false],
  ['IF-GW-149', 'GET', '/api/v1/ops/timeline', 'gateway.ops.timeline', false, null, false],
  ['IF-GW-150', 'GET', '/api/v1/ops/logs', 'gateway.ops.logs', false, null, true],
  ['IF-GW-151', 'GET', '/api/v1/ops/logs/tail', 'gateway.ops.logs_tail', false, null, false],
  ['IF-GW-152', 'GET', '/api/v1/ops/tripwires', 'gateway.ops.tripwires', false, null, false],
  ['IF-GW-153', 'PUT', '/api/v1/ops/tripwires/settings', 'gateway.ops.tripwire_settings', true, null, false],
  ['IF-GW-154', 'GET', '/api/v1/ops/autostart', 'gateway.ops.autostart', false, null, false],
  ['IF-GW-155', 'PUT', '/api/v1/ops/autostart', 'gateway.ops.autostart_put', true, null, false],
  ['IF-GW-156', 'POST', '/api/v1/ops/services/{svc}:restart', 'gateway.ops.service_restart', true, null, false],
  ['IF-GW-157', 'GET', '/api/v1/ops/slo', 'gateway.ops.slo', false, null, false],
  ['IF-GW-160', 'GET', '/api/v1/settings', 'gateway.settings.get', false, null, false],
  ['IF-GW-161', 'PATCH', '/api/v1/settings', 'gateway.settings.patch', true, null, false],
  ['IF-GW-162', 'GET', '/api/v1/settings/policies', 'gateway.settings.policies', false, null, false],
  ['IF-GW-163', 'POST', '/api/v1/settings/policies:preview', 'gateway.settings.policies_preview', true, 60000, false],
  ['IF-GW-164', 'POST', '/api/v1/settings/policies:switch', 'gateway.settings.policies_switch', true, null, false],
  ['IF-GW-165', 'POST', '/api/v1/settings/onboarding', 'gateway.settings.onboarding', true, null, false],
  ['IF-GW-166', 'PUT', '/api/v1/settings/pause', 'gateway.settings.pause_put', true, null, false],
  ['IF-GW-167', 'DELETE', '/api/v1/settings/pause', 'gateway.settings.pause_delete', true, null, false],
  ['IF-GW-168', 'PUT', '/api/v1/settings/dday', 'gateway.settings.dday_put', true, null, false],
  ['IF-GW-169', 'DELETE', '/api/v1/settings/dday', 'gateway.settings.dday_delete', true, null, false],
  ['IF-GW-170', 'POST', '/api/v1/settings/declarations', 'gateway.settings.declarations', true, null, false],
  ['IF-GW-171', 'GET', '/api/v1/cards', 'gateway.cards.list', false, null, true],
  ['IF-GW-172', 'POST', '/api/v1/cards/{card_id}:suspend', 'gateway.cards.suspend', true, null, false],
  ['IF-GW-173', 'POST', '/api/v1/cards/{card_id}:retire', 'gateway.cards.retire', true, null, false],
  ['IF-GW-174', 'POST', '/api/v1/cards/{card_id}:resume', 'gateway.cards.resume', true, null, false],
  ['IF-GW-180', 'GET', '/api/v1/cli/status', 'gateway.cli.status', false, null, false],
  ['IF-GW-181', 'POST', '/api/v1/cli/shutdown', 'gateway.cli.shutdown', true, null, false],
  ['IF-GW-182', 'POST', '/api/v1/cli/doctor', 'gateway.cli.doctor', true, null, false],
  ['IF-GW-183', 'POST', '/api/v1/cli/session-key:rotate', 'gateway.cli.rotate_session_key', true, null, false],
  ['IF-GW-184', 'POST', '/api/v1/cli/backups', 'gateway.cli.backup', true, null, false],
  ['IF-GW-185', 'POST', '/api/v1/cli/restores', 'gateway.cli.restore', true, null, false],
  ['IF-GW-186', 'POST', '/api/v1/cli/exports', 'gateway.cli.export', true, null, false],
  ['IF-GW-187', 'POST', '/api/v1/cli/imports', 'gateway.cli.import', true, null, false],
  ['IF-GW-188', 'POST', '/api/v1/cli/capture', 'gateway.cli.capture', true, null, false],
  ['IF-GW-189', 'GET', '/api/v1/cli/packs', 'gateway.cli.packs', false, null, false],
  ['IF-GW-190', 'POST', '/api/v1/cli/packs', 'gateway.cli.packs_action', true, null, false],
  ['IF-GW-191', 'GET', '/api/v1/cli/packs/installs/{install_id}', 'gateway.cli.pack_install', false, null, false],
  ['IF-GW-192', 'POST', '/api/v1/cli/autostart', 'gateway.cli.autostart', true, null, false],
  ['IF-GW-193', 'POST', '/api/v1/cli/upgrade', 'gateway.cli.upgrade', true, null, false],
  ['IF-GW-194', 'GET', '/api/v1/cli/operations/{op_id}', 'gateway.cli.operation', false, null, false],
  ['IF-GW-195', 'POST', '/api/v1/cli/blueprints', 'gateway.cli.blueprint_import', true, null, false],
  ['IF-GW-199', 'GET', '/internal/v1/activity', 'gateway.internal.activity', false, null, false],
];
