// markdown: 결과서 공통 렌더링(표·이스케이프·생성 표지). 순수 함수.

/** 모든 생성 결과서의 첫 줄(STD-DOC-07). */
export const GENERATED_MARK = '<!-- generated by tools/si-docs — 수기 편집 금지 (STD-DOC-07) -->';

/** 표 셀 이스케이프: `|` → `\|`, 줄바꿈 → 공백. */
export function escapeCell(value: string | number | boolean | null | undefined): string {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ');
}

/** 마크다운 표(머리 + 구분선 + 행). 행이 없으면 머리만. */
export function table(headers: string[], rows: (string | number | boolean | null | undefined)[][]): string {
  const head = `| ${headers.map(escapeCell).join(' | ')} |`;
  const sep = `|${headers.map(() => '---').join('|')}|`;
  const body = rows.map((r) => `| ${r.map(escapeCell).join(' | ')} |`);
  return [head, sep, ...body].join('\n');
}

/** 생성 표지 + 본문. 항상 끝 줄바꿈 1개. */
export function document(lines: string[]): string {
  return `${[GENERATED_MARK, ...lines].join('\n').replace(/\n+$/, '')}\n`;
}

/** 소요 시간(ms) 표기: 1.2s · 3m04s. */
export function formatDuration(ms: number): string {
  if (ms < 1000) {
    return `${Math.round(ms)}ms`;
  }
  const s = ms / 1000;
  if (s < 60) {
    return `${s.toFixed(1)}s`;
  }
  const m = Math.floor(s / 60);
  return `${m}m${String(Math.round(s - m * 60)).padStart(2, '0')}s`;
}

/** 퍼센트 표기(소수 1자리). 값 없음 = n/a. */
export function formatPct(pct: number | null): string {
  return pct === null ? 'n/a' : `${pct.toFixed(1)}%`;
}

/** 직전 대비 %p 표기. 부호는 `+`·`−`(U+2212). */
export function formatDelta(delta: number | null): string {
  if (delta === null) {
    return '';
  }
  const abs = Math.abs(delta).toFixed(1);
  return ` (${delta < 0 ? '−' : '+'}${abs}%p)`;
}
